### ISSUE TITLE
Request for updating Meep on Ubuntu

### ISSUE THREAD

**Issue by jiwonyune** [stevengj/meep#10]
I am using Meep on Ubuntu. I was trying to use the step function "dft-ldos", but I got an error saying "Unbound variable: dft-ldos". Later, I found out that MEEP on Ubuntu is outdated (current version is 1.1.1, http://packages.ubuntu.com/trusty/meep). This update would appeal to many people currently using Ubuntu. 

Thank you.

**Comment by gexc** [comment]
Maybe you should contact the ubuntu maintainers?
It is more convenient to compile the source yourself to keep it up to date.

**Comment by jiwonyune** [comment]
I tried to compile the source myself, but I kept having a problem during the installation. I couldn't figure out a way to fix it. It kept saying there is a problem with gen-ctl-io. Because I am not a Linux expert, only option I have left is to use "apt-get install".

I just sent an email to the Ubuntu maintainer. Thanks for the advise.

**Comment by gexc** [comment]
You could also try debian testing, where a newer version of meep is available.
https://packages.debian.org/jessie/meep

**Comment by stevengj** [comment]
The Debian package should eventually migrate to Ubuntu.

(Regarding installation, you have to read the `installation paths` section of the manual very carefully, especially if you have already installed Meep etcetera via `apt-get`.   The key thing is to tell the `configure` script where to find the desired versions of the stuff you are compiling.  e.g. you can modify the `PATH` to tell it where to find the latest `gen-ctl-io`.)

**Comment by FilipDominec** [comment]
1) I spent few days compiling latest version of MEEP; the result that should work out-of-the-box is at http://fzu.cz/~dominecf/meep/index.html#install

2) I have been tempted for a long time to make a Personal Package Archive with the latest version of MEEP and Python-MEEP compiled for easy installation. It would take some time to refresh my Ubuntu-packaging skills, but it may help many people to start with MEEP. Shall I do it?

**Comment by stevengj** [comment]
If you do, I would be happy to post a link.
