### ISSUE TITLE
Python import error simulation.py

### ISSUE THREAD

**Issue by RJTK** [stevengj/meep#107]
I installed meep with the Python interface, essentially following the procedure here: https://www.mail-archive.com/meep-discuss@ab-initio.mit.edu/msg05819.html

In addition to including the flags '--with-python', and '--enable-shared' which I deduced were necessary from looking at configure.sh.

After running make install, 'import meep' failed with a message about missing 'simulation.py'.  I found that simulation.py had simply not been copied to .../site-packages/meep/, and manually doing so seemed to fix the problem.  I couldn't find anything relevant in the Makefiles except

`PY_PKG_FILES = \
    __init__.py              \
    $(srcdir)/geom.py        \
    $(srcdir)/simulation.py  \
    $(srcdir)/source.py      \
    .libs/_meep.so
`
In any case, I'm guessing there was some small bug in the install process, perhaps someone else will corroborate this experience.

**Comment by ChristopherHogan** [comment]
Thanks for pointing this out.  This should be fixed with #108.

**Comment by RJTK** [comment]
Bueno, that was fast.
