### ISSUE TITLE
pymeep error: libgfortran.so.3: cannot open shared object file

### ISSUE THREAD

**Issue by Tagussan** [stevengj/meep#143]
Hi.
I have installed pymeep following [this instruction](https://gist.github.com/ChristopherHogan/c22bb7cc7248f7595c4b09d0e3b16735); however, when I try to run waveguide example [here](https://meep.readthedocs.io/en/latest/Python_Tutorials/Basics/), I got this error: 

`ImportError: libgfortran.so.3: cannot open shared object file: No such file or directory.`

I confirmed that PYTHONPATH and LD_LIBRARY_PATH are empty.
I'm using Arch Linux.

Thank you.

**Comment by Tagussan** [comment]
I confirmed that PYTHONPATH and LD_LIBRARY_PATH  are empty.

**Comment by ChristopherHogan** [comment]
With your meep environment active, try
`conda install libgfortran=3`

**Comment by Tagussan** [comment]
Now I'm able to run the example successfully. Thank you!
