### ISSUE TITLE
Unable to build libctl

### ISSUE THREAD

**Issue by chrispo-m** [stevengj/meep#149]
I'm attempting to build Meep 1.3 to run under Windows via Cygwin64, following the steps [here](https://novelresearch.weebly.com/installing-meep-in-windows-8-via-cygwin.html).

Unfortunately I'm stuck attempting to build libctl.  There's no configure file found, and the autogen.sh errors out with "autoreconf:  command not found"

Any words of wisdom?

thanks,
Chris

**Comment by stevengj** [comment]
You need to install autoconf for this to work.  There is a cygwin package for it.
