### ISSUE TITLE
Can't compile after installing

### ISSUE THREAD

**Issue by erny123** [stevengj/meep#154]
Hi All,

I've installed everything as instructed on the installation page of MEEP. 
Ive installed harminv, openmpi, hdf5, and openblas. I anstalled meep using:

`sudo apt-get install meep h5utils`

Ok. Then I go to tutorials and try to compile using:

` g++ -malign-double tutorial1.cpp -o tutorial1 -lmeep -lhdf5 -lz -lgsl -lharminv -llapack -lcblas -latlas -lfftw3 -lm`

output:
`tutorial1.cpp:1:20: fatal error: meep.hpp: No such file or directory
compilation terminated.`

**Comment by stevengj** [comment]
You need to install the `libmeep-dev` package to get the header files.
