### ISSUE TITLE
Compiling with MPB

### ISSUE THREAD

**Issue by hmaarrfk** [stevengj/meep#17]
Hi,

MPB updated their eigensolver interface

This breaks compilation with meep.

I think the appropriate fix is
https://github.com/hmaarrfk/meep-rpm/blob/master/meep-patch1_newmpbEigensolver.patch

Cheers,

**Comment by stevengj** [comment]
Yes, but the changes are only in the git `master` version of MPB, which most people shouldn't be using.   Once there is a new release of MPB I will update Meep.
