### ISSUE TITLE
meep segfaults

### ISSUE THREAD

**Issue by keithbriggs** [stevengj/meep#180]
How do I debug this (on Ubuntu 16, with latest meep version)?

kbriggs> ./try_meep_01.py
-----------
Initializing structure...
Segmentation fault (core dumped)

**Comment by keithbriggs** [comment]
I narrowed this down to: if you give Cone a center value which is a float (instead of a Vector3), then it accepts the argument but segfaults at runtime.   Shouldn't it reject the argument at compile time?

**Comment by ChristopherHogan** [comment]
Thanks @keithbriggs. I'll add some type checking.
