### ISSUE TITLE
No rule to make target `meep.py'

### ISSUE THREAD

**Issue by acmcclung** [stevengj/meep#184]
I recently downloaded meep-1.4.1. While calling ``make`` I encounter the error

``
make[2]: *** No rule to make target `meep.py', needed by `all'.  Stop.
``

when I ``./configure --without-python && make`` I am able to successfully install, but I was hoping to check out the new Python interface. Any thoughts about what might cause this?

**Comment by oskooi** [comment]
This is being addressed by #183. In the meantime, you can install PyMeep using the [installation instructions](http://meep.readthedocs.io/en/latest/Installation/#building-from-source) provided in the documentation (which builds using the GitHub source, not the tarball).

**Comment by stevengj** [comment]
Fixed by #185.
