### ISSUE TITLE
Simulating Very Large Strucutres

### ISSUE THREAD

**Issue by m9631m** [stevengj/meep#186]
Hello,

I am using meep in Ubuntu from apt-get.

My simulation runs for lower resolutions but when I increase the resolution I get this error
meep: Cannot split -287473792 grid points into 3 parts

I would like to simulate structures as large as 150 * lambda but I get similar errors.

Thank you, 
Mahdad.

**Comment by m9631m** [comment]
Hello Everyone,
It seems it is a meep-mpi issue. When I tried the exact same file with serial meep, it passed the initial levels but during eps-averaging I get another error:
.
.
.
subpixel-averaging is 95.9594% done, 0.168456 s remaining
subpixel-averaging is 97.083% done, 0.120225 s remaining
subpixel-averaging is 98.2088% done, 0.0730027 s remaining
subpixel-averaging is 99.3353% done, 0.0267789 s remaining
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted (core dumped)

**Comment by stevengj** [comment]
Thanks for the bug report.  Yes, it looks like the `grid_volume::split(int n, int which)` function (and similar) should take a 64-bit integer argument, not an `int` (which overflows at about 1300×1300×1300).

**Comment by stevengj** [comment]
See also #25.

**Comment by stevengj** [comment]
Should be fixed on master by #193.
