### ISSUE TITLE
field-energy-in-box and MPI

### ISSUE THREAD

**Issue by pavlo2014** [stevengj/meep#19]
Dear All,

I am not sure that it is a bug, but decided to report it any way. There is a chance that it is a local problem of our computer cluster but it could be an issue with MEEP.

In my script, I have this command:
'(define-param EQW1 (field-energy-in-box (volume (center 0 0 zQW1) (size wbox wbox tQW))))'
It supposed to calculate energy in a layer.

Meep fails to do this and throws out an error message
[node127:121267] *** An error occurred in MPI_Allreduce
[node127:121267] *** reported by process [1095958529,1946303531564662784]
[node127:121267] *** on communicator MPI_COMM_WORLD
[node127:121267] *** MPI_ERR_IN_STATUS: error code in status
[node127:121267] *** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
[node127:121267] ***    and potentially your MPI job)

This is the error message of MEEP build with OpenMPI 1.8.3. If MEEP is build with support of MPICH2 2.1, then attempts to run the code sometimes end with a similar error message.

What it interesting:
Meep throws out the error randomly (or I cannot spot any systematic behaviour). 5-6 out to 10 attempts to run this code end with the error (the rest of attempts end with a success). The error occurs only when I use multiple nodes.

Compiler: icc 14.0.0 (gcc version 4.4.7 compatibility)

Any help is appreciated.

Let me know if you need more information.

best wishes

p.s. many thanks for adding far field calculations in meep.

**Comment by pavlo2014** [comment]
Just to let you know that I found a workaround. Using GCC rather than Intel compiler resolves the problem. Tested with mvapich2 2.1 and latest stable versions of MPB and MEEP.

**Comment by stevengj** [comment]
You may need to be consistent in your compilers — use the same compiler that you used to compile MPI.

**Comment by pavlo2014** [comment]
Yes, I was using the same compiler that used to compile MPI. This combination of icc 14.0.0 + MPICH2 2.1 also worked well before. Problems appeared last week.

It seems that it was a local problem. Something has been changed I am not aware of. 

thank you
