### ISSUE TITLE
Overloaded function 'fields_output_hdf5' in python __init__.py file

### ISSUE THREAD

**Issue by DerekK88** [stevengj/meep#190]
Hello,

I just installed the latest version of parallel meep (1.4.2) with python from source using the build instructions on the installation page.  Everything built correctly (make checks passed) and works well with scheme, but when I try to output fields using the python meep library I get the following error:
...
  File "/usr/local/lib/python2.7/site-packages/meep/__init__.py", line 2878, in output_hdf5
    return _meep.fields_output_hdf5(self, *args)

NotImplementedError: Wrong number or type of arguments for overloaded function 'fields_output_hdf5'.
  Possible C/C++ prototypes are: ....``

I think the latest version of SWIG (I am using SWIG 3.0.8-0ubuntu3, Guile 2.0.11) gave me a bad python wrapper?  Any ideas how I might workaround this?

Thanks!
Derek

**Comment by ChristopherHogan** [comment]
Hello.  SWIG 3.0.8 should work fine. If `make check` passes, as you say, that implies `output_hdf5` is working correctly. Can you share the code that gave you the error?

**Comment by DerekK88** [comment]
Hello,

Thanks for the quick response.  I was running the [straight waveguide example](https://meep.readthedocs.io/en/latest/Python_Tutorials/Basics/#a-straight-waveguide) which causes the issue at `sim.run(mp.at_beginning(mp.output_epsilon),
        mp.at_end(mp.output_efield_z),
        until=200)`.  Note that it runs ok if I change this to `sim.run(until=200)`, indicating it seems to be an issue with saving fields to hdf5.

I'm using anaconda2 with python2.7 and installed meep via:
`git clone https://github.com/stevengj/meep.git`
`cd meep/`
`sh autogen.sh --enable-shared --with-mpi PYTHON=/home/derek/anaconda2/bin/python \
    CC=mpicc CXX=mpic++ LDFLAGS="${MY_LDFLAGS}" CPPFLAGS="${MY_CPPFLAGS}"`
`make && make check && sudo make install`

**The complete python interpreter output is below:**
`Using MPI version 3.1, 1 processes

Initializing structure...
Traceback (most recent call last):

  File "<ipython-input-1-8b1fc4cbf5bd>", line 1, in <module>
    runfile('/home/derek/MEEP/tutorials/pymeep_2dwaveguide/2dwaveguide.py', wdir='/home/derek/MEEP/tutorials/pymeep_2dwaveguide')
  File "/home/derek/anaconda2/lib/python2.7/site-packages/spyder/utils/site/sitecustomize.py", line 710, in runfile
    execfile(filename, namespace)
  File "/home/derek/anaconda2/lib/python2.7/site-packages/spyder/utils/site/sitecustomize.py", line 93, in execfile
    builtins.execfile(filename, *where)
  File "/home/derek/MEEP/tutorials/pymeep_2dwaveguide/2dwaveguide.py", line 34, in <module>
    until=200)
  File "/usr/local/lib/python2.7/site-packages/meep/simulation.py", line 911, in run
    self._run_until(until, step_funcs)
  File "/usr/local/lib/python2.7/site-packages/meep/simulation.py", line 494, in _run_until
    _eval_step_func(self, func, 'step')
  File "/usr/local/lib/python2.7/site-packages/meep/simulation.py", line 983, in _eval_step_func
    func(sim, todo)
  File "/usr/local/lib/python2.7/site-packages/meep/simulation.py", line 1026, in _beg
    _eval_step_func(sim, f, todo)
  File "/usr/local/lib/python2.7/site-packages/meep/simulation.py", line 981, in _eval_step_func
    func(sim)
  File "/usr/local/lib/python2.7/site-packages/meep/simulation.py", line 1266, in output_epsilon
    sim.output_component(mp.Dielectric)
  File "/usr/local/lib/python2.7/site-packages/meep/simulation.py", line 774, in output_component
    self.fields.output_hdf5(c, vol, h5, append, self.output_single_precision, self.get_filename_prefix())
  File "/usr/local/lib/python2.7/site-packages/meep/__init__.py", line 2878, in output_hdf5
    return _meep.fields_output_hdf5(self, *args)

NotImplementedError: Wrong number or type of arguments for overloaded function 'fields_output_hdf5'.
  Possible C/C++ prototypes are:
    meep::fields::output_hdf5(meep::h5file *,char const *,int,meep::component const *,meep::field_function,void *,int,meep::volume const &,bool,bool)
    meep::fields::output_hdf5(meep::h5file *,char const *,int,meep::component const *,meep::field_function,void *,int,meep::volume const &,bool)
    meep::fields::output_hdf5(meep::h5file *,char const *,int,meep::component const *,meep::field_function,void *,int,meep::volume const &)
    meep::fields::output_hdf5(char const *,int,meep::component const *,meep::field_function,void *,meep::volume const &,meep::h5file *,bool,bool,char const *,bool)
    meep::fields::output_hdf5(char const *,int,meep::component const *,meep::field_function,void *,meep::volume const &,meep::h5file *,bool,bool,char const *)
    meep::fields::output_hdf5(char const *,int,meep::component const *,meep::field_function,void *,meep::volume const &,meep::h5file *,bool,bool)
    meep::fields::output_hdf5(char const *,int,meep::component const *,meep::field_function,void *,meep::volume const &,meep::h5file *,bool)
    meep::fields::output_hdf5(char const *,int,meep::component const *,meep::field_function,void *,meep::volume const &,meep::h5file *)
    meep::fields::output_hdf5(char const *,int,meep::component const *,meep::field_function,void *,meep::volume const &)
    meep::fields::output_hdf5(char const *,int,meep::component const *,meep::field_rfunction,void *,meep::volume const &,meep::h5file *,bool,bool,char const *)
    meep::fields::output_hdf5(char const *,int,meep::component const *,meep::field_rfunction,void *,meep::volume const &,meep::h5file *,bool,bool)
    meep::fields::output_hdf5(char const *,int,meep::component const *,meep::field_rfunction,void *,meep::volume const &,meep::h5file *,bool)
    meep::fields::output_hdf5(char const *,int,meep::component const *,meep::field_rfunction,void *,meep::volume const &,meep::h5file *)
    meep::fields::output_hdf5(char const *,int,meep::component const *,meep::field_rfunction,void *,meep::volume const &)
    meep::fields::output_hdf5(meep::component,meep::volume const &,meep::h5file *,bool,bool,char const *)
    meep::fields::output_hdf5(meep::component,meep::volume const &,meep::h5file *,bool,bool)
    meep::fields::output_hdf5(meep::component,meep::volume const &,meep::h5file *,bool)
    meep::fields::output_hdf5(meep::component,meep::volume const &,meep::h5file *)
    meep::fields::output_hdf5(meep::component,meep::volume const &)
    meep::fields::output_hdf5(meep::derived_component,meep::volume const &,meep::h5file *,bool,bool,char const *)
    meep::fields::output_hdf5(meep::derived_component,meep::volume const &,meep::h5file *,bool,bool)
    meep::fields::output_hdf5(meep::derived_component,meep::volume const &,meep::h5file *,bool)
    meep::fields::output_hdf5(meep::derived_component,meep::volume const &,meep::h5file *)
    meep::fields::output_hdf5(meep::derived_component,meep::volume const &)`

**Comment by DerekK88** [comment]
Thanks for the comment.  I figured out what was going on, and it had to do with running the code in spyder (nothing intrinsic to meep).  However, it works perfectly on the command line, so I'm going to go ahead and close this issue.
