### ISSUE TITLE
Drude metal material with material function-defined geometry fails  

### ISSUE THREAD

**Issue by kitchenknif** [stevengj/meep#197]
Defining the geometry by a material function that uses materials with DrudeSusceptibiltiy/LorentzianSusceptibility fails with error  "meep: susceptibilities in user-defined-materials not yet supported". 

Am I doing something wrong, or is this correct behavior? According to the manual, materials with susceptibilities are supported by material functions.

Minimal Python script to reproduce error -
[MaterialFunctionMinimal.zip](https://github.com/stevengj/meep/files/1697723/MaterialFunctionMinimal.zip)

**Comment by stevengj** [comment]
It's supported in Scheme, but not yet supported in the Python interface:  https://github.com/stevengj/meep/blob/f33efca4b8f0cd373f641babd9b8250d725c0455/libmeepgeom/meepgeom.cpp#L639-L646

**Comment by kitchenknif** [comment]
Yeah, I saw that and was confused. :(
Thanks for clearing that up.
