### ISSUE TITLE
Eigenmode source calculated at wrong position in 3D

### ISSUE THREAD

**Issue by highbag** [stevengj/meep#20]
Hi everybody,

when I have a 3d geometry of a straight waveguide, parallel to the z-direction and I use the eigenmode-source on one side, I get the correct eigenmode there and thus the correct propagation through the waveguide.
Anyway, when I taper the waveguide for example and again use the eigenmode source at one end of the waveguide, I do not get the correct eigenmode! After testing I found out, that the eigenmode is always calculated in the z-center. Means: Even if I place the eigenmode source at one end of the waveguide, let's say (center 0 0 14) (size sx sy 0), the eigenmode is calculated at (center 0 0 0) (size sx sy 0).
Not even the (eig-lattice-center 0 0 14) (eig-lattice-size sx sy 0) commands can change this.

Can somebody confirm this bug?

Best regards
Marc

**Comment by stevengj** [comment]
Looks like this is a typo in `mpb/src/mpb.cpp`.  Can you tell me whether the following patch fixes the problem?
```
--- a/src/mpb.cpp
+++ b/src/mpb.cpp
@@ -46,7 +46,7 @@ static void meep_mpb_eps(symmetric_matrix *eps,
   const double *s = eps_data->s;
   const double *o = eps_data->o;
   vec p(eps_data->dim == D3 ?
-       vec(o[0] + r[0] * s[0], o[1] + r[1] * s[1], o[1] + r[1] * s[1]) :
+       vec(o[0] + r[0] * s[0], o[1] + r[1] * s[1], o[2] + r[2] * s[2]) :
        (eps_data->dim == D2 ?
         vec(o[0] + r[0] * s[0], o[1] + r[1] * s[1]) :
         /* D1 */ vec(o[2] + r[2] * s[2])));
```

**Comment by highbag** [comment]
It does fix the problem. Thanks alot!!!
As I can see, you already implemented the patch correctly. As it is actually   MEEP/src/mpb.cpp
and

--- mpb.cpp.orig	2015-05-06 16:54:25.000000000 +0200
+++ mpb.cpp	2015-07-14 18:29:15.751092859 +0200
@@ -46,7 +46,7 @@
   const double *s = eps_data->s;
   const double *o = eps_data->o;
   vec p(eps_data->dim == D3 ?
-	vec(o[0] + r[0] * s[0], o[1] + r[1] * s[1], o[1] + r[1] * s[1]) :
+	vec(o[0] + r[0] * s[0], o[1] + r[1] * s[1], o[2] + r[2] * s[2]) :
 	(eps_data->dim == D2 ?
 	 vec(o[0] + r[0] * s[0], o[1] + r[1] * s[1]) :
 	 /* D1 */ vec(o[2] + r[2] * s[2])));

**Comment by highbag** [comment]
It does fix the problem. 
As I can see, you already implemented the patch correctly. As it is actually MEEP/src/mpb.cpp
and

![snapshot1](https://cloud.githubusercontent.com/assets/6420128/8696527/45fcd430-2aed-11e5-9af3-7b3ecd590d6e.png)

Thanks alot and best regards from Zurich
Marc
