### ISSUE TITLE
2/3D FEM EM solver

### ISSUE THREAD

**Issue by berceanu** [stevengj/meep#208]
Does meep implement any FEM for solving magnetostatic problems? I did a quick search and came up with the following alternatives:

[Poisson Superfish](http://laacg.lanl.gov/laacg/services/download_sf.phtml): 2D, win-only
[xfemm](https://sourceforge.net/p/xfemm/wiki/Home): 2D, Linux, Octave interface 
[Radia](http://www.esrf.eu/Accelerators/Groups/InsertionDevices/Software/Radia): 3D, win-only, Mathematica interface
[FEniCS](https://fenicsproject.org), 3D, Linux, Python interface, but low-level
There is also Comsol of course, but I restricted myself to FOSS.

Ideally we want 2&3D capability, and Linux compatibility, are there plans to implement this or could you please point me in the right direction?

Finally, here is an [example](http://onlinelibrary.wiley.com/doi/10.1002/cmr.b.20018/epdf) to get some idea of the type of modelling we are interested in.

**Comment by stevengj** [comment]
No, meep is neither FEM nor is it for static problems.

**Comment by berceanu** [comment]
And you are not aware of any such code?
