### ISSUE TITLE
meep not linking with fftw3_mpi

### ISSUE THREAD

**Issue by amrit-poudel** [stevengj/meep#22]
Hi,
I compiled (with gcc 4.8.3)  mpi version of meep (v 1.3) with mpi version of fftw3 (single threaded, static library, libfftw3_mpi.a).

I am confident that my meep installation is fine since I have ran many simulations and compared numerical and analytical results. 

However, when I tried computing LDOS, which requires Fourier transform and is already implemented in meep, I get the following error during linking. 

monitor.cpp:(.text+0x2c87): undefined reference to `fftw_plan_dft_1d'
monitor.cpp:(.text+0x2c92): undefined reference to `fftw_execute'
monitor.cpp:(.text+0x2c9a): undefined reference to `fftw_destroy_plan'

I have  -lfftw3_mpi linker and have correctly set -L and -I flags to the folder where my libfttw3_mpi.a file is located.

I am not sure why meep looks for fftw, instead of fftw3_mpi.

**Comment by stevengj** [comment]
Meep uses the serial version of FFTW, even when Meep itself is parallel, so you need libfftw3 installed.

**Comment by amrit-poudel** [comment]
Thanks. That worked.
