### ISSUE TITLE
LDOS in 2D  

### ISSUE THREAD

**Issue by amrit-poudel** [stevengj/meep#23]
I tried comparing LDOS computed in meep with analytical value in vacuum, but could not get the two results agree.

Analytically, LDOS in 2D = 2*\omega/(\pi c^2) \* Tr[ Im [G] ], G = dyadic Greens function of the vacuum. In 2D, Im[G] = 1/4, for all three diagonal components. 

I use a continuous-wave point source at a fixed frequency to compute the LDOS at that frequency and at that location(I could use other temporal sources to get LDOS at several frequencies in a single FDTD run, but for now, I just want to compare the numerical with analytical results and for simplicity I choose a continuous-wave source).

I am using meep as a c++ library and use dft_ldos object with update and ldos functions to compute the LDOS.

The result is off by an order of magnitude.

What is the unit of LDOS in 2D in meep?

**Comment by stevengj** [comment]
See http://ab-initio.mit.edu/wiki/index.php/Meep_Tutorial/Local_density_of_states

**Comment by stevengj** [comment]
(Don't use a CW source, use a gaussian pulse.  You want something that decays in time so that you can stop the simulation after a finite time and have the (discrete-time) Fourier transform.  For a CW source, the accumulated Fourier transform grows linearly with time.)

**Comment by amrit-poudel** [comment]
Thank you for your suggestion. 

Just so I understand, does meep perform  discrete Fourier transform  at each FDTD time step and then sums up the result to obtain the final value?

**Comment by stevengj** [comment]
Yes, it accumulates a DTFT of the fields at each timestep, as described here: http://ab-initio.mit.edu/wiki/index.php/Meep_Introduction#Transmission.2Freflection_spectra

**Comment by amrit-poudel** [comment]
Thanks again.

I tried computing LDOS in 2D in vacuum using a Gaussian source. As far as I understand, the Gaussian source in meep = exp(i*w*t)*Gaussian envelope.  I choose angular frequency, w = 0.00997 (in meep units) and fwidth =w.

I ran the simulation for 20*period, where period = 2*\pi/w. By this time, source obviously dies out, so the DTFT should just work fine.

Then I compute LDOS (in a frequency range: w-fwidth/2 to w+fwidth/2) numerically, but this does not agree with the analytical value given by: 
LDOS = 2*w/(\pi c^2) * Tr[ Im [G] ] =   0.00476, where I used c =1, Tr[Im[G]] = 3/4. G is dimensionless in 2D.

I am confident about my computational setup (width  of pml, choice of frequency, computational domain, etc) since I can reproduce the analytical value of the Greens function using a cw-source.
Yet, for some reason, LDOS does not seem right.

The analytical formula of LDOS (and the corresponding factor of 2, due to electric+magnetic, and \pi, etc) is consistent with the formula given in chapter 4 of your online text book.

**Comment by amrit-poudel** [comment]
Sorry, I had to reopen this issue again.  I noticed that LDOS computed by meep seems to  depend on the location of the point source, which should not be the case in vacuum. I find this behavior very strange. The numerical LDOS agrees with analytical result at some locations  but deviates  at others.

**Comment by stevengj** [comment]
Does it converge with resolution?

**Comment by amrit-poudel** [comment]
No, it does not converge with resolution.


I directly compute LDOS from meep in a 2D free space, and then compare the numerical solution with the following analytical expression:

2*w/pi*Im[G_{zz}], where Im[G_{zz}] = 1/4


For instance, for w = 0.166 (in meep units), I get following results:

(a) For resolution = 2
LDOS = 5.053142e-2  (meep)

(b) For resolution = 4
LDOS = 4.676034e-2  (meep)


Theoretical value of LDOS  is 0.166667. Clearly, increasing resolution does not work.


For the record, I am using 
a  =1e-2 m
\lambda = 6*a
pml thickness = 100*a
 computational region Lx = Ly = 710*a.

Source point  is located at (Lx/2, Ly/2).


I run the simulation for 20*period, where period = 1/frequency.

**Comment by amrit-poudel** [comment]
I noticed that dft_ldos.ldos() function returns different results on a single processor vs multiple processors.

Could this be a bug or is there a different way to run ldos simulation on multiple nodes/processors that I am unaware of?


I compute ldos on multiple nodes/processors using meep-mpi:

initialize mpi(argc, argv);

Call dft_ldos.ldos() function to compute ldos.

**Comment by amrit-poudel** [comment]
Is there a quick way to fix this bug other than running simulation on a single core? 

As soon as I use multiple processors, I get incorrect LDOS, even for free space.

**Comment by amrit-poudel** [comment]
https://github.com/stevengj/meep/blob/master/src/dft_ldos.cpp

In the above source code, in  line 106,  you have:

EJ += double(fr[idx]) * conj(A);


What is this quantity EJ? Is it the E-field or the product of the E-field and the current source J? 


If it is really the product of E-field and the current source J, how is this formula

real(Fdft[i] * conj(Jdft[i])) / abs2(Jdft[i]);  (line 60 in the source code)

 consistent with eq. 4.22 in the your online textbook http://arxiv.org/pdf/1301.5366v1.pdf  ?

**Comment by amrit-poudel** [comment]
What exactly  is the quantity EJ  one line 135 in the source code https://github.com/stevengj/meep/blob/master/src/dft_ldos.cpp?

If EJ is really the integral of E and J, is there a way to obtain a Fourier transform of E-field alone  in meep?

Also, if  EJ is the integral of E times J, how is this consistent with Eq. 4.22 in your paper http://arxiv.org/pdf/1301.5366v1.pdf? 


I am interested in calculating the E-field (both real and imaginary parts) for a point dipole source as a function of frequency in a given frequency window, together with LDOS in a single FDTD run. I do not want to use the frequency domain solver.

**Comment by erikshipton** [comment]
I ran into problems with LDOS using multiple processors and a random phase of the point source.  When using multiple processors I get a different LDOS every time I run the same exact problem.  On a single processor the same LDOS is calculated every run.  

I'm also getting a different near2far result when using the random phased point source on multiple processors each time I run the same exact problem.  On a single processor I get the same near2far each run.

**Comment by oskooi** [comment]
This is a bug in dft_ldos which occurs whenever a point source is placed between two chunks (e.g., placing a source at the origin and using more than one processor). The serial version, as you have noticed, is unaffected since the non-PML regions are not divided into chunks.

The issue is related to an over-counting of Jsum in dfot_ldos::update as a single source is duplicated within two chunks during the source initialization (i.e., src_vol_chunkloop in sources.cpp). A possible fix would involve determining that the source has been duplicated and then to properly scale Jsum. This check would need to happen at each time step which is inefficient.

An alternative approach may be to add a new flag member to dft_ldos which is set during the source initialization to indicate that a source duplication has occurred.
