### ISSUE TITLE
Meep + MPB not working

### ISSUE THREAD

**Issue by sunilkpai** [stevengj/meep#237]
I am using the anaconda installation of Meep since it is very nicely packaged together. I noticed that when I installed chogan's packages, I still could not get MPB to talk to Meep when attempting the command `from meep import mpb`. I want to avoid installing from source (I checked that and it works) and stick with a virtual environment. Any suggestions on how to get MPB to compile correctly with Meep in the conda environment? Note: I am using Ubuntu 16.04! (Tagging @ChristopherHogan to see if he can give any insight here!)

**Comment by ChristopherHogan** [comment]
The conda packages don't contain the python MPB wrappers yet. Once the MPB wrappers are finalized, we will likely have another release. At that time, new conda packages with pyMPB will be created. Until then, compiling from source is the only way to get access to MPB from python.
