### ISSUE TITLE
Interactive Python Meep on Multiple Processors

### ISSUE THREAD

**Issue by smartalecH** [stevengj/meep#249]
The documentation [mentions](https://meep.readthedocs.io/en/latest/Parallel_Meep/) that you cannot run Meep interactively on multiple processors. I assume this means for us python users, you can't leverage multiple processors within an iPython/ Jupyter notebook.

There's a [parallelized](https://ipyparallel.readthedocs.io/en/latest/intro.html) version of iPython gaining traction within the community. This implementation supports message passing via MPI. Does this mean that the meep architecture could potentially run in parallel on this framework?

A feature like this would be very useful for demos and tutorials.

**Comment by stevengj** [comment]
As long as the processes are launched with MPI, then Meep (compiled with `--with-mpi`) should work as-is.  (Meep Python initializes MPI with `mpi4py`.)
