### ISSUE TITLE
Errors running the python meep script in the old example folder

### ISSUE THREAD

**Issue by nootherme** [stevengj/meep#256]
Dear Meep Users, 

Using Ubuntu 16.04LTS, I followed the instruction by Filip Dominec to install python meep via the shell file "python-meep-install.sh" in his post. The installation was successful, I believe, since I was able to import the meep_mpi module. However, when I run one of the example scripts called python_meep_harminv_ring_numpy_matrix.py". It gives the following error message: 
"NotImplementedError: Wrong number or type of arguments for overloaded function 'fields_output_hdf5'  "

In addition, I noticed that, in the version of the python-meep I was able to install, unlike the tutorial in the Meep documentation for python, the class or method "block" doesn't appear to exist.

I am wondering whether I was installing the wrong version of meep or was it possible that the old examples are not compatible? Any advice is highly appreciated. 

Thanks a lot.

Cheers,
Zhou

**Comment by oskooi** [comment]
You will need to install the official version of PyMeep following the instructions in the [documentation](http://meep.readthedocs.io/en/latest/Installation/). The Python interface you have installed is the unofficial version which was developed independently. The two versions are incompatible. This is described in the [FAQ](http://meep.readthedocs.io/en/latest/FAQ/#is-there-a-python-interface).
