### ISSUE TITLE
Build error (problem in pympb.cpp) "Cannot convert cnumber to mpb_real {aka double}"

### ISSUE THREAD

**Issue by DerekK88** [stevengj/meep#269]
Hi,

I'm encountering a new issue when building meep from source.  I get the following error message when at the meep "make" step:

`pympb.cpp: In member function ‘void py_mpb::mode_solver::material_epsmu(meep_geom::material_type, symmetric_matrix*, symmetric_matrix*, bool)’:
pympb.cpp:563:20: error: cannot convert ‘cnumber’ to ‘mpb_real {aka double}’ in assignment
         epsmu->m01 = md->medium.epsilon_offdiag.x;`

The compilation then aborts.  Any idea what might be going on?  The build script I had was working with previous versions of meep.  Below is my build script:

Thank you!

```#!/bin/bash

set -e

RPATH_FLAGS="-Wl,-rpath,/usr/local/lib:/usr/lib/x86_64-linux-gnu/hdf5/openmpi"
MY_LDFLAGS="-L/usr/local/lib -L/usr/lib/x86_64-linux-gnu/hdf5/openmpi ${RPATH_FLAGS}"
MY_CPPFLAGS="-I/usr/local/include -I/usr/include/hdf5/openmpi"

export CC=mpicc
export CXX=mpic++

cd ~/install
git clone https://github.com/stevengj/mpb.git
cd mpb/
sh autogen.sh --enable-shared CC=mpicc CXX=mpic++ LDFLAGS="${MY_LDFLAGS}" CPPFLAGS="${MY_CPPFLAGS}"
make && sudo make install

sudo pip install --upgrade pip
pip install --no-cache-dir mpi4py
export HDF5_MPI="ON"
pip install --no-binary=h5py h5py

cd ~/install
git clone https://github.com/stevengj/meep.git
cd meep/
sh autogen.sh --enable-shared --with-mpi PYTHON=/home/dkita/anaconda2/bin/python \
    CC=mpicc CXX=mpic++ LDFLAGS="${MY_LDFLAGS}" CPPFLAGS="${MY_CPPFLAGS}"
make && sudo make install

**Comment by ChristopherHogan** [comment]
#257, which was merged 6 days ago, fixed an issue where the installed MPB, if compiled without the `--with-hermitian-eps` flag, would be incompatible with the python MPB interface in meep.  Are you seeing this problem with the latest source from the master branch? Do you have MPB installed?

**Comment by DerekK88** [comment]
I am building from https://github.com/stevengj/meep.git and https://github.com/stevengj/mpb.git, which I believe are the master branches.

I have a previous version of meep and mpb (from January) installed, but I am now trying to install the newer meep + mpb

**Comment by DerekK88** [comment]
Installing MPB with the `--with-hermitian-eps` flag fixes the installation error.  Should it have installed `ok` without this though?

Also, with it installed now I am trying to run the [mode decomposition example here](https://meep.readthedocs.io/en/latest/Python_Tutorials/Mode_Decomposition/)

But am getting `AttributeError: 'Simulation' object has no attribute 'get_eigenmode_coefficients'
`.  Perhaps this is a separate issue?

**Comment by ChristopherHogan** [comment]
Yes, it should work without the `--with-hermitian-eps` flag. I can reproduce the problem and am working on it.

Regarding mode decomposition, `get_eigenmode_coefficients` isn't quite ready yet for Python. You can track the progress at #248.

**Comment by DerekK88** [comment]
Thanks for the response.  I appreciate all the work going into this project and am looking forward to the features you are all adding!
