### ISSUE TITLE
typechecking error in meep/simulation.py

### ISSUE THREAD

**Issue by DerekK88** [stevengj/meep#278]
Python meep seems to return a type-error when you set `epsilon_input_file` with a string (`epsilon_input_file="somefile.h5"`).  The type-error happens at the `set_materials_from_geometry()` call in meep/simulation.py (line 396).  However, casting it to a string fixes this:

`epsilon_input_file=str("somefile.h5")`.

I think this might be fixed, if line [394](https://github.com/stevengj/meep/blob/7998e6dc96eac709211f923128021bddbb9b7ee1/python/simulation.py) of `simulation.py` is changed from:

`self.default_material = self.epsilon_input_file`

to:

`self.default_material = str(self.epsilon_input_file)`

**Comment by ChristopherHogan** [comment]
Adding the `str()` call as you suggest won't hurt anything (I've created PR #279), but I'm curious why you're experiencing this behavior. I couldn't reproduce the issue with Python 2.7, 3,4 or 3.6. Which version of Python are you using? What is the full error message you see?

**Comment by stevengj** [comment]
Maybe you are passing a Unicode string in Python 2, e.g. maybe you imported `unicode_literals`?

**Comment by DerekK88** [comment]
Ah, yes, I am importing `unicode_literals`.  That seems to be the cause of this error.

This library is often imported to make python 3 scripts/libraries backwards compatible with both Python 2, so it would be nice if meep could read unicode strings (so long as it doesn't unjustly complicate things).

Perhaps the the str() typecasting could be added at line 275 (and similarly at 291 for `filename_prefix`) rather than at 394?
