### ISSUE TITLE
Plane wave source example could include epsilon

### ISSUE THREAD

**Issue by andrewjgross** [stevengj/meep#287]
I was trying to crib from the  meep/python/examples/pw-source.py for a case where I want the PW source inside a medium with eplison=4.

It took some fiddling before I realized that I needed to include a Sqrt(eps) term in the amplitude function as below.  I understand the example says its for vacuum, but it could be helpful for new users  to include a note about using it in a medium.

```
def pw_amp(k, x0, eps):
    `def` _pw_amp(x):
        return cmath.exp(1j * k.dot(x + x0)*math.sqrt(eps))
    return _pw_amp

```
Then I called it as:
```
sources = [
    mp.Source(
        mp.ContinuousSource(fcen, fwidth=df),
        component=mp.Ez,
        center=mp.Vector3(-0.5 * s, 0),
        size=mp.Vector3(0, s),
        amp_func=pw_amp(k, mp.Vector3(x=-0.5 * s),4)
    ),
    mp.Source(
        mp.ContinuousSource(fcen, fwidth=df),
        component=mp.Ez,
        center=mp.Vector3(0, -0.5 * s),
        size=mp.Vector3(s, 0),
        amp_func=pw_amp(k, mp.Vector3(y=-0.5 * s),4)
    )
]
```

**Comment by stevengj** [comment]
Yes, but note that the factor of the refractive index should be included in the wavevector k itself, not just in the pw_amp function. (This matters if you use k again somewhere else, such as in a boundary condition.)

**Comment by stevengj** [comment]
A PR to the docs would be welcome.

**Comment by stevengj** [comment]
I updated the example.
