### ISSUE TITLE
ImportError: libgsl.so.19: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by kannesito** [stevengj/meep#290]
This occurs, after installing PyMeep via Conda package manager, starting python from the virtual environment and then importing meep:

~/conda$ python
Python 3.6.5 |Anaconda, Inc.| (default, Mar 29 2018, 18:21:58) 
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import meep
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/hannes/conda/envs/mp/lib/python3.6/site-packages/meep/__init__.py", line 8, in <module>
    from . import _meep
ImportError: libgsl.so.19: cannot open shared object file: No such file or directory

Best regards,
Hannes

**Comment by stevengj** [comment]
@ChristopherHogan, if the Conda meep is linked to libgsl, then presumably it should be linking/distributed with a Conda GSL package?

**Comment by ChristopherHogan** [comment]
The conda recipe for pymeep specifies libgsl as a dependency, so a libgsl conda package should be installed when the environment is created. 

Can you paste the output of `conda info`, `conda list`, and show the exact commands you used to create the environment? I am unable to reproduce this.

Thanks.

**Comment by ChristopherHogan** [comment]
On further investigation, it looks like Anaconda released a new GSL package than what the pymeep package was built with. You can resolve this by downgrading libgsl to the correct version as follows:
```bash
conda install gsl=2.2.1
```
For the next release, I'll pin the versions to make sure this doesn't happen again.

**Comment by kannesito** [comment]
Thanks, installing gsl=2.2.1 solved the problem! ;)

**Comment by cpjisha** [comment]
Thank you. This was an issue for me too and installing gsl in the meep env solved the problem.
