### ISSUE TITLE
Make fails: libmeep error

### ISSUE THREAD

**Issue by luismpriede** [stevengj/meep#303]
I am trying to install meep-1.4.3 on Fedora 26. Configure ran without errors but Make stopped with the error:
  CXXLD    libmeep.la
/usr/bin/ld: //usr/local/lib/libmpb.a(libmatrices_la-eigensolver.o): relocation R_X86_64_32 against `.rodata.str1.8' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: //usr/local/lib/libmpb.a(libmatrices_la-eigensolver_utils.o): relocation R_X86_64_32 against `.rodata.str1.8' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: //usr/local/lib/libmpb.a(libmatrices_la-evectmatrix.o): relocation R_X86_64_32 against `.rodata.str1.8' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: //usr/local/lib/libmpb.a(libmatrices_la-linmin.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: //usr/local/lib/libmpb.a(libmatrices_la-matrices.o): relocation R_X86_64_32 against `.rodata.str1.8' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: //usr/local/lib/libmpb.a(libmatrices_la-minpack2-linmin.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: //usr/local/lib/libmpb.a(libmatrices_la-sqmatrix.o): relocation R_X86_64_32 against `.rodata.str1.8' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: //usr/local/lib/libmpb.a(libmaxwell_la-maxwell.o): relocation R_X86_64_32 against `.rodata.str1.8' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: //usr/local/lib/libmpb.a(libmaxwell_la-maxwell_constraints.o): relocation R_X86_64_32 against `.rodata.str1.8' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: //usr/local/lib/libmpb.a(libmaxwell_la-maxwell_eps.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: //usr/local/lib/libmpb.a(libmaxwell_la-maxwell_op.o): relocation R_X86_64_32 against `.rodata.str1.8' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: //usr/local/lib/libmpb.a(libmaxwell_la-maxwell_pre.o): relocation R_X86_64_32 against `.rodata.str1.8' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: //usr/local/lib/libmpb.a(mpi_utils.o): relocation R_X86_64_32 against `.rodata.str1.8' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: //usr/local/lib/libmpb.a(libmatrices_la-blasglue.o): relocation R_X86_64_32 against `.rodata.str1.8' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: Nonrepresentable section on output
collect2: error: ld returned 1 exit status
make[3]: *** [Makefile:502: libmeep.la] Error 1
make[3]: Leaving directory '/root/Downloads/meep-1.4.3/src'
make[2]: *** [Makefile:432: all] Error 2
make[2]: Leaving directory '/root/Downloads/meep-1.4.3/src'
make[1]: *** [Makefile:506: all-recursive] Error 1
make[1]: Leaving directory '/root/Downloads/meep-1.4.3'
make: *** [Makefile:415: all] Error 2

I install mpb and libctl with some issues but solving these at the end of the day.

Thanks

**Comment by stevengj** [comment]
You need to install libmpb as a shared library: when you compile MPB, use the `--enable-shared` flag to the configure script.

See also the Ubuntu script in the manual — http://meep.readthedocs.io/en/latest/Build_From_Source/
