### ISSUE TITLE
validity check for the materials library

### ISSUE THREAD

**Issue by stevengj** [stevengj/meep#319]
Since the material fits are only valid in given range of wavelengths (and assume a particular distance unit), it would be good to print a warning if the user attempts use them outside this range.   To do this, we could:

1. Add an optional field to the Python `Medium` data structure (not sent to C++) which indicates a range of valid frequencies.  By default, this would be None, but the materials library would set it.

2. Before the simulation runs, the Python would call a `simulation.check_material_frequencies` function that would print a warning if any source frequency (± bandwidth) or DFT frequency in the simulation falls outside the valid frequencies for any of the materials in the geometry or extra_materials list.

**Comment by ChristopherHogan** [comment]
I have a couple questions about this.

1. I'm not sure where to get the "DFT frequency." Can you point me to an object and member?
2. If an `fwidth` kwarg was given to a source constructor, then the `width` property (bandwidth I assume) is actually `1 / width`. Do I need to worry about that when checking "source frequency (± bandwidth)?"
3. Do we need to worry about `CustomSource`?

Here is my current implementation:
```python
    def _check_material_frequencies(self):

        # TODO: Need to handle CustomSource?
        # TODO: s.src.width is 1 / s.src.width if fwidth kwarg was given
        source_freqs = [(s.src.frequency, s.src.width) for s in self.sources
                        if hasattr(s.src, 'frequency')]

        # TODO: Where do these come from?
        dft_freqs = []

        materials_with_freq_range = []
        for mat in [go.material for go in self.geometry] + self.extra_materials:
            if isinstance(mat, mp.Medium) and mat.valid_freq_range:
                materials_with_freq_range.append(mat)

        warn_src_fmt = "source frequency {} is out of material's range of {}-{}"
        warn_dft_fmt = "DFT frequency {} is out of material's range of {}-{}"

        for m in materials_with_freq_range:
            min_freq = m.valid_freq_range.min
            max_freq = m.valid_freq_range.max

            for sf in source_freqs:
                if sf[0] + sf[1] > max_freq or sf[0] - sf[1] < min_freq:
                    warnings.warn(warn_src_fmt.format(sf, min_freq, max_freq), RuntimeWarning)

            for dftf in dft_freqs:
                if dftf > max_freq or dftf < min_freq:
                    warnings.warn(warn_dft_fmt.format(dftf, min_freq, max_freq), RuntimeWarning)
```

**Comment by stevengj** [comment]
By "DFT frequency" I mean the `freq_min, freq_max` passed to things like `add_dft_fields`, `add_dft_flux`, etcetera.  These are stored in things like the `dft_flux` object as `freq_min` and `freq_min+Nfreq*dfreq` (see https://github.com/stevengj/meep/blob/3dd5789bdffe68d592a179a689d983b057099cd6/src/meep.hpp#L957-L958)

**Comment by stevengj** [comment]
For source frequency you would use `fcen ± fwidth` or equivalently `fcen ± (1/width)`.

**Comment by stevengj** [comment]
I would suggest starting with a method `valid_material_frequencies()` that returns a `(freq_min, freq_max)` that works for all of the materials.  This is just the intersection of `(0, Inf)` with that of all of the materials: `freq_min` is the *maximum* of all the frequency minimums (or 0 if no materials have a frequency range) and `freq_max` is the *minimum* of all the maximums (or Inf if none).

Then, once you have this range, you can loop over the sources etcetera to check that they are within the range.   This way you only have to check each source once, not once per material.

I wouldn't worry about custom sources.
