### ISSUE TITLE
Broadband S-Parameter Sweep

### ISSUE THREAD

**Issue by smartalecH** [stevengj/meep#359]
I am using the `get_eigenmode_coefficients()` function to extract the forward and backward propogation coefficients of the fundamental mode for an arbitrary structure (similar to what's done in the [mode decomposition tutorial](https://github.com/stevengj/meep/blob/master/python/examples/mode-decomposition.py)). I'm hoping to use these coefficients to extract the S Parameters of the device.

Is it possible to sweep for multiple frequencies at once? I noticed the `add_eigenmode()` function allows you to specify the number of frequency bins (`nfreq`). When I pass the corresponding flux object into `get_eigenmode_coefficients()`, however, I can only retrieve the corresponding coefficients for the  center frequency.

I looked into using the `kpoint_func` parameter, but didn't find very much documentation (other than the original pull request: #323)

**Comment by stevengj** [comment]
@ChristopherHogan, is this a bug in the Python interface?

In [simulation.py](https://github.com/stevengj/meep/blob/b29d33a1b64770551f90118ca2ba45e29752900e/python/simulation.py#L1039-L1040) it allocates a `coeffs` array of length `2 * num_bands`, but in [fields::get_eigenmode_coefficients](https://github.com/stevengj/meep/blob/master/src/mpb.cpp#L601-L607) it seems that the array should have length `2 * num_bands * num_freqs` (the docstring is missing the factor of 2), which I would allocate as a 2d array `np.zeros(2 * num_bands, flux. Nfreq, dtype=np.complex128)`.

**Comment by ChristopherHogan** [comment]
Yes, it looks like a bug. It should be fixed in #360.

**Comment by smartalecH** [comment]
I manually fixed it on my end, and it seemed to solve the problem. It also took care of some random segmentation faults I would get, probably due to the funky allocation discrepancies. Thanks for the quick reply!
