### ISSUE TITLE
meep.mbp not recognized as installed by python; iPython sees it

### ISSUE THREAD

**Issue by soamaven** [stevengj/meep#362]
### Issue: MBP not being found by python interpreter
I've build `meep` from source in order to access the `python` interface for both `meep` and `mbp`. I am compiling OpenBLAS first ([recomended](http://meep.readthedocs.io/en/latest/Build_From_Source/#blas-and-lapack) in the docs when using `mbp`), installing that to my conda environment, and linking to that. `meep` seems to install just fine, but importing the `mbp` sub-module is not possible. It could be that I am using the wrong compiler options, but simplifying them as much as possible gives the same end results.
### Expected results:
Python script and iPython can find meep.mbp when importing

#### Part a) Running a simple import script 
```
#!/home/user/anaconda3/envs/py36meep/bin/python
import meep
import meep.mbp as mbp
```
gives:
```
Using MPI version 2.2, 1 processes
Traceback (most recent call last):
  File "/home/user/install/trace_mbp.py", line 4, in <module>
    import meep.mbp as mbp
ModuleNotFoundError: No module named 'meep.mbp'

Elapsed run time = 0.0007 s
```
#### Part b) Using iPython:
```
(py36meep) user@localhost:~$ ipython
Python 3.6.5 |Anaconda, Inc.| (default, Apr 29 2018, 16:14:56) 
Type 'copyright', 'credits' or 'license' for more information
IPython 6.4.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import meep
Using MPI version 2.2, 1 processes

In [2]: import meep.mbp
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-2-355456a11d08> in <module>()
----> 1 import meep.mbp

ModuleNotFoundError: No module named 'meep.mbp'

In [3]: import meep.mpb
Segmentation fault (core dumped)
```
Above, line `[3]` is using the "Tab" autocompletion to find `mbp` in the `meep` namespace. If it is selected and user hits _enter_, the whole kernel segfaults.

### Bash install script:
```
#!/bin/bash

# Installation on Ubuntu 16.04

# All of these are installed -- commented out
#____________________________________
# sudo apt-get update
# sudo apt-get -y install     \
#     libblas-dev             \
#     liblapack-dev           \
#     libgmp-dev              \
#     swig                    \
#     libgsl-dev              \
#     autoconf                \
#     pkg-config              \
#     libpng16-dev            \
#     git                     \
#     guile-2.0-dev           \
#     libfftw3-dev            \
#     libhdf5-openmpi-dev     \
#     hdf5-tools              \
#     libpython3.5-dev        \
#     python3-numpy           \
#     python3-scipy           \
#     python3-matplotlib      \
#     python3-pip             \
# ____________________________________

# Trying to get this installed into a conda virtual environment to keep my system tidy
# One should create this environment before running the script
CONDATRGTENV="py36meep"
INSTALL_PATH="$HOME/anaconda3/envs/$CONDATRGTENV"

# Force script to use anaconda bins first; make sure there isn't any other path pollution from
# my .bashrc PATH variable
# basic functions such as cp, mkdir, etc. are in /bin
# gfortran and gcc are needed from /usr/bin
PATH="${INSTALL_PATH}/bin:/usr/bin:/bin"

# ["Must go faster" -J. Goldblum](https://giphy.com/gifs/7XsFGzfP6WmC4/html5)
echo "performance" | sudo tee /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor

# Using a separate directory to build the sources
SRCBUILDDIR=$HOME/src_build
mkdir -p $SRCBUILDDIR

# ____________Optional?_______________
# ________Compile OPENBLAS____________
# Go to build directory and clone repo
# cd $HOME/src_build
# git clone git@github.com:xianyi/OpenBLAS.git
# cd OpenBLAS
# git checkout release-0.3.0
# make && make install PREFIX="$INSTALL_PATH"
# # ____________________________________

set -e  # What is this for? From meep docs example script

# Modified from the meep install from source docs to use anaconda environment libraries
# This should help make things all compatible... right?
RPATH_FLAGS="-Wl,-rpath,${INSTALL_PATH}/lib:${INSTALL_PATH}/include/openmpi"
MY_LDFLAGS="-L${INSTALL_PATH}/lib -L${INSTALL_PATH}/include/openmpi ${RPATH_FLAGS}"
MY_CPPFLAGS="-I${INSTALL_PATH}/include -I${INSTALL_PATH}/include/openmpi"

# Go to build directory and clone repo
cd $SRCBUILDDIR
git clone https://github.com/stevengj/harminv.git
cd ~/src_build/harminv/
# make and install harminv into conda env
# -lgfortran flag is recommended by OpenBLAS manual for LAPACK linking
# https://github.com/xianyi/OpenBLAS/wiki/User-Manual#link-the-library
sh autogen.sh --enable-shared --prefix=$INSTALL_PATH
make && make install

# Go to build directory and clone repo
cd $SRCBUILDDIR
git clone https://github.com/stevengj/libctl.git
cd libctl/
# make and install libctl into conda env
sh autogen.sh --enable-shared --prefix=$INSTALL_PATH 
make && make install

# Go to build directory and clone repo
cd $SRCBUILDDIR
git clone https://github.com/stevengj/h5utils.git
cd h5utils/
# make and install h5utils into conda env
sh autogen.sh --prefix=$INSTALL_PATH CC=mpicc LDFLAGS="${MY_LDFLAGS}" CPPFLAGS="${MY_CPPFLAGS}"
make && make install

# Go to build directory and clone repo
cd $SRCBUILDDIR
git clone https://github.com/stevengj/mpb.git
cd mpb/
# make and install mbp into conda env
# mpicc and mpic++ have been confirmed to be aliased to the conda bins
# LDFLAGS and CPPFLAGS should point to libraries/headers in the conda env as defined above
# Is the PYTHON=python3 superfluous?
#  -lpthread -lgfortran flags are recommended by OpenBLAS manual for threaded and LAPACK linking, respectively
# https://github.com/xianyi/OpenBLAS/wiki/User-Manual#link-the-library
sh autogen.sh --enable-shared CC=mpicc CXX=mpic++\
	--prefix=$INSTALL_PATH \
	LDFLAGS="${MY_LDFLAGS} -lpthread -lgfortran" \
	CPPFLAGS="${MY_CPPFLAGS}" --with-hermitian-eps
make && make install

pip3 install --upgrade pip
# Some more edification on why mpi4py and h5py should be installed with these options would be nice
# They come pre-installed with conda, so maybe this is an issue
pip3 install --user --no-cache-dir mpi4py
export HDF5_MPI="ON"  # What does this do...? Sets HDF5 to run multithreaded I assume
pip3 install --user --no-binary=h5py h5py

# Go to build directory and clone repo
cd $SRCBUILDDIR
rm -rf meep
git clone https://github.com/stevengj/meep.git
cd meep/

# make and install meep into conda env
#  -lpthread -lgfortran flags are recommended by OpenBLAS manual for threaded and LAPACK linking, respectively
# https://github.com/xianyi/OpenBLAS/wiki/User-Manual#link-the-library

# For some reason, all the other compliatrions find openblas; meep finds generic blas unless specified
sh autogen.sh --enable-shared --with-mpi CC=mpicc CXX=mpic++\
		--prefix=$INSTALL_PATH \
		PYTHON=python3 \
    LDFLAGS="${MY_LDFLAGS}" \
    CPPFLAGS="${MY_CPPFLAGS}" \
    --with-blas=$INSTALL_PATH/lib/libopenblas.so
make && make install

echo "conservative" | sudo tee /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor

```
Full terminal output can be [found here](https://paste.ubuntu.com/p/6y5gy3qjMC/). 90%+ of it is the OpenBLAS compile output.
### Notes:
- [Example script](http://meep.readthedocs.io/en/latest/Build_From_Source/#building-from-source) in the documentation give same results. (install path is modified only)

- Conda env does not have a guile package (system does). During `libctl` build it ouputs:
   ```
   checking for guile-config... guile-config
   checking if linking to guile works... yes
   checking libguile.h usability... yes
   checking libguile.h presence... yes
   checking for libguile.h... yes
   checking guile/gh.h usability... no
   checking guile/gh.h presence... no
   checking for guile/gh.h... no
   ```
  - I am not interested in the scheme interface, so I didn't really look into this. Seems odd that some bits are found.

- Not sure why when compiling `mpb` `-lopenblas` is found, but not with `meep` compilation. I have to use the `--with-blas` flag, otherwise it will use `-lbas`. This is not indicated in the linked output, since I specified the blas library, but was observed previously.

- There are some [`LDFLAGS` recommended on the OpenBLAS wiki](https://github.com/xianyi/OpenBLAS/wiki/User-Manual#link-the-library) that were used. `-lpthread` and `-lgfortran` are specified to be used when linking threaded libraries or LAPACK, respectively. Results are same with and without these flags.

- `mpi4py` and `h5py` were already installed by conda, so the `pip3` line doesn't really do anything. Maybe this is an issue?

- Last, the docs are out of date. It advises to use `./configure`, but this doesn't work, autoconf takes care of this now it seems?

**Comment by ChristopherHogan** [comment]
Instead of `import meep.mbp as mbp`, can you try `import meep.mpb as mpb`?

**Comment by soamaven** [comment]
I am assuming you meant `import mbp`? 

I can't even reproduce my results from yesterday with the same script at this point.

Now I am getting:
`Attempting to use an MPI routine before initializing MPICH`

when trying to import `meep`

**Comment by ChristopherHogan** [comment]
> I am assuming you meant import mbp?

No, `mpb`. You have the acronym wrong. **M**IT **P**hotonic **B**ands. :)

Is there some incorrect documentation somewhere that says `mbp`?

**Comment by soamaven** [comment]
Haha :grimacing: yes that was one of my issues! The Internet forever knows my dyslexia.

I am still having the issue that MPB is not compiling correctly though, when trying to use an optimized BLAS and LAPACK library.

I have to say, the documents are out of date and still refer to using the `configure` script, while the masters are using `autogen.sh` now.

**Comment by ChristopherHogan** [comment]
> I am still having the issue that python MPB is not compiling/working correctly though, when trying to use an optimized BLAS and LAPACK library.

What error are you getting?

> I have to say, the documents are out of date and still refer to using the configure script, while the masters are using autogen.sh now.

Most of the documentation assumes the use of a source distribution (i.e., the Github release tarballs available [here](https://github.com/stevengj/meep/releases)).  In that case, the `configure` script must be used. On the other hand, if you're building from the tip of the `master` branch in the repository, then you have to use `autogen.sh`, which creates the `configure` script. For the latter case, the correct instructions are [here](http://meep.readthedocs.io/en/latest/Build_From_Source/#building-from-source).

Also, I see you're using the MPI version of Meep.  Currently, the Python interface to MPB does not support MPI, so it must be run with only one process.

**Comment by soamaven** [comment]
I have tried a lot of things at this point, but probably the fact that MPB doesn't support MPI is my issue -- I was getting an MPI error when loading the module.

Is there any hope for MPI MPB? I am planning to eventually move to an HPC environment (which supports conda envs, hence the effort to contain everything there). I guess I can't say at this point if it will even be needed.

Thanks! I don't know why I didn't find the correct instructions before, maybe I wasn't paying close attention the docs version. I'll give this a try and get back to you with specific errors.

**Comment by ChristopherHogan** [comment]
> Is there any hope for MPI MPB?

We plan to support it, but I can't say when that will happen. You may find that the serial version will be fast enough.

Also, If you have the `hdf5-openmpi-dev` package installed, be aware that the default `mpi4py` conda package uses MPICH. You may have a conflict there. I've built a version that uses openmpi that can be installed from my channel: `conda install -c chogan -c conda-forge mpi4py`.

**Comment by soamaven** [comment]
So I found a few different ways to compile MEEP with MPB in conda environments. I am having one last issue that I could use help with. But I am closing this, I had a lot of environment variables incorrect. Closing this, going to open a new issue in addition to posting some gists with compilation scripts for compiling MEEP in (mostly) isolated conda environments. Thanks for the help here!
