### ISSUE TITLE
Output K vector with get_eigenmode_coefficients()

### ISSUE THREAD

**Issue by smartalecH** [stevengj/meep#363]
Would it be too difficult (or even practical) to modify the `get_eigenmode_coefficients()` python function to also output the computed k vector magnitude and group velocity? It's often nice to have the accompanying mode index and group index for S Parameter sweeps. Currently, I just run a separate analysis using the MPB python interface, but this seems overly redundant.

Obtaining the group velocity, for example, seems trivial since we could pass an array into `self.fields.get_eigenmode_coefficients()` (rather than `None`). Would it be straightforward to pull out the corresponding k vector as well?

**Comment by stevengj** [comment]
It would be straightforward to modify the code to return this information, I agree.

**Comment by smartalecH** [comment]
I'm working on a fix. Retrieving the group velocity through both the C++ and python interfaces are rather easy. Retrieving the corresponding k vector is a bit more challenging. In the C interface, I simply call the `get_k()` function and store the resulting `vec` object in an array -- similar to what's done with `coeffs` and `vgrp`. Passing this preallocated array from the python interface to the C++ interface using SWIG is the tricky part.

Is there a recommended way to pass a list of preallocated Vector3 objects generated in python to the C++ interface? For some reason, numpy doesn't like generating a numpy array of Vector3 objects, so that doesn't seem like an easy solution to me.

Alternatively, I could extract out the individual x,y and z components of the k vector and store those in a simple array. It's probably cleaner to return the original `vec` /  `Vector3` object, however.
