### ISSUE TITLE
Python Tutorial: AttributeError: 'Simulation' object has no attribute 'get_flux_data'

### ISSUE THREAD

**Issue by AniketPant02** [stevengj/meep#370]
Hello all,

I am brand new to MEEP and FDTD. I am using a Python 3.6 environment with the latest Conda environment for Parallel-PyMEEP installed on Ubuntu 16.04 *(fresh install)*.  Upon running the Transmission Spectrum tutorial (_bend_flux.py_) it returns an error:

`AttributeError: 'Simulation' object has no attribute 'get_flux_data'`

How can I circumvent this error?

Thanks all for your help.

**Comment by ChristopherHogan** [comment]
Hi. `get_flux_data` was added to the library after the latest conda package was built. I'm currently experimenting with creating nightly development builds. You could try creating an environment with the bleeding edge dev package like this:
```bash
conda create -n devmeep -c chogan/label/dev -c chogan -c conda-forge pymeep-parallel nomkl
``` 
That will have all the latest source as of a few hours ago.

**Comment by AniketPant02** [comment]
Thank you very much for the speedy reply! Problem solved and saved me from a build from source. :)
