### ISSUE TITLE
get_eigenmode_coefficients() Negative Center Bug

### ISSUE THREAD

**Issue by smartalecH** [stevengj/meep#380]
There may be a bug in the `get_eigenmode_coefficients()` routine (hopefully it's just my implementation). I drew a simple 2D waveguide and ran two simulations. One simulation centered the waveguide above the origin and pulled the eigenmode coefficients for the fundemental mode at two ports. The next simulation did the same, but on the other side of the axis. For some reason, `get_eigenmode_coefficients()` doesn't like any negative Y values. I found some more weird effects when simulating ring resonators (I'll work on some simple examples later).

![image](https://user-images.githubusercontent.com/24902086/41316665-2850348c-6e50-11e8-815f-05918def05a1.png)

![image](https://user-images.githubusercontent.com/24902086/41316678-34f8116e-6e50-11e8-9f0a-4d83d26f133a.png)

[debug_get_eig.py.zip](https://github.com/stevengj/meep/files/2095821/debug_get_eig.py.zip)

**Comment by stevengj** [comment]
@HomerReid will take a look.

**Comment by HomerReid** [comment]
Fixed in #391. Thanks for the bug report, and especially for taking the time to supply a MWE and helpful plots.

**Comment by smartalecH** [comment]
For documentation purposes, the change does indeed fix the bug:

![bottom](https://user-images.githubusercontent.com/24902086/41986266-de496e72-79f2-11e8-895e-6ac2a466aa4a.png)

Thanks for the update!
