### ISSUE TITLE
Cannot implement 3 or more prisms, get "bug 1 in find_best_partition" error

### ISSUE THREAD

**Issue by DerekK88** [stevengj/meep#384]
Hi all,

I'm getting an interesting error: `bug 1 in find_best_partition` or `bug 2 in find_best_partition` when implementing 3 or more prism objects in meep.  Interestingly, it works totally fine with 1 or 2 prisms, but adding any more will cause this error to be thrown.

I attached a simple [MWE](https://github.com/stevengj/meep/files/2100058/multiple_prisms.zip) if you'd like to try reproducing the issue (I'm working off the latest meep,mpb,&libctl built from source).

The file should throw the error as is, but if you comment out the 3rd prism object in the geometry list (line 48), it will run.

Thanks,
Derek

**Comment by HomerReid** [comment]
Thanks for the bug report. I will investigate.

**Comment by DerekK88** [comment]
Is this an issue other people are getting too?  If not, I can see if it's something odd with my meep build

**Comment by stevengj** [comment]
Homer just checked in some prism fixes into the libctl master branch — does that fix the problem?

**Comment by HomerReid** [comment]
I can confirm that this problem is resolved by the fix implemented in stevengj/libctl#17 (now merged into the libctl master branch). Using the MWE supplied in the original bug report, I was able to reproduce the issue reported before the fix, and to confirm that it was resolved after the fix.

**Comment by DerekK88** [comment]
Yes, the libctl fix appears to resolve this (as well as in some other tests I have), so I'll mark it as closed.  Thanks @HomerReid!

**Comment by HomerReid** [comment]
Thank *you* for the bug report and especially for furnishing an MWE.
