### ISSUE TITLE
Documentation about materials question

### ISSUE THREAD

**Issue by kitchenknif** [stevengj/meep#386]
The documentation for how meep handles dispersive materials includes a formula for Drude-Lorentz dispersion, that is significantly different from models I've seen in FDTD-related literature.

Equation from your documentation:
![render2](https://user-images.githubusercontent.com/8235105/41518934-a2320392-72f7-11e8-9210-c1c9ae72554f.png)

Equation from, e.g., [doi:10.1016/j.cplett.2007.08.027](https://doi.org/10.1016/j.cplett.2007.08.027) 
![render1](https://user-images.githubusercontent.com/8235105/41518974-df134258-72f7-11e8-803a-8f4700414ad3.png)

For the model used and data from [dot:10.1364/AO.37.005271](https://doi.org/10.1364/AO.37.005271), these two models would be equivalent, because conductivity is set to zero. 
But for fits where the conductivity is not zero, these two models are vastly different. 

Am I misunderstanding something here?

**Comment by stevengj** [comment]
They are inequivalent when you have both σ and Lorentzians, but since both of them have to be fit to experimental data and both have the same asymptotic behavior it doesn't seem like a problem.
