### ISSUE TITLE
Is it necessary to output the eps data with solver.py?

### ISSUE THREAD

**Issue by smartalecH** [stevengj/meep#387]
https://github.com/stevengj/meep/blob/4602ac8c81751905c265b2543e11cac3847cfa20/python/solver.py#L769-L777

From the above code snippet, it looks to me that a temporary h5 file containing eps information is saved to the disk in order to eventually share the computation across multiple processes. While I'm sure this helps alleviate the strain for very large simulations, it dramatically slows down batch simulations -- especially when running `find_k()` multiple times.

There may be a better way to preserve this functionality without writing to the disk each function call. Any thoughts?

**Comment by stevengj** [comment]
Yes, I think it makes sense to change the MPB Python interface to be more like Meep in this respect (only output ε if the user specifically requests it).
