### ISSUE TITLE
oblique planewave in 2d cell with PML fails to fully decay away

### ISSUE THREAD

**Issue by oskooi** [stevengj/meep#471]
As mentioned recently in #399, an oblique planewave pulsed source in a 2d computational cell with PML boundaries along one direction fails to fully decay away. This is demonstrated by snapshots of the scalar field at equal intervals throughout the time stepping in the following simulation script (`pw_oblique.py`). The planewave has an arbitrary angle of 22.9° and the default material has homogeneous index of `1.5`. 

The snapshots were created using [h5utils](https://github.com/stevengj/h5utils/blob/master/README.md) via `h5topng -vZc bluered pw_oblique-ez-000*.h5`. Note that the `-R` flag was omitted in order to set the colormap range for each snapshot individually. From the snapshots, there appears to be non-negligible fields remaining in the cell long after the source has turned off. These fields are propagating *normal* to the PML which are therefore not absorbed. Everything works fine if the source is normally incident (i.e., `theta_in = 0`). The results are unaffected by increasing the length of the PMLs.

A failure of the fields to fully decay away prevents the simulation from being terminated using the `stop_when_fields_decayed` routine which is often used for pulsed sources. This makes computing the incident flux used for normalization less accurate.

```py
import meep as mp
import math
import cmath

resolution = 50        # pixels/μm                                                                                                                                      

dpml = 1.0             # PML thickness                                                                                                                                  
dmat = 10              # length of material                                                                                                                             

sx = dpml+dmat+dpml
sy = 5

cell_size = mp.Vector3(sx,sy,0)
pml_layers = [mp.PML(thickness=dpml,direction=mp.X)]

fcen = 1               # center frequency (wavelength = 1 μm)                                                                                                           
df = 0.2               # frequency width                                                                                                                                

ng = 1.5
glass = mp.Medium(index=ng)

# angle of incident planewave; CCW about Y axis, 0 degrees along +X axis                                                                                                
theta_in = math.radians(22.9)

# k (in vacuum) with correct length (plane of incidence: XY)                                                                                                            
k = mp.Vector3(math.cos(theta_in),math.sin(theta_in),0).scale(fcen)
if theta_in == 0:
  k = mp.Vector3(0,0,0)

def pw_amp(k,x0):
  def _pw_amp(x):
    return cmath.exp(1j*2*math.pi*ng*k.dot(x+x0))
  return _pw_amp

src_pt = mp.Vector3(-0.5*sx+dpml+0.3*dmat,0,0)
sources = [mp.Source(mp.GaussianSource(fcen,fwidth=df),
                     component=mp.Ez,
                     center=src_pt,
                     size=mp.Vector3(0,sy,0),
                     amp_func=pw_amp(k,src_pt))]

sim = mp.Simulation(resolution=resolution,
                    cell_size=cell_size,
                    boundary_layers=pml_layers,
                    k_point=k,
                    default_material=glass,
                    sources=sources)

sim.run(mp.at_every(7.3,mp.output_efield_z), until_after_sources=100)
```

![pw_oblique_snapshots](https://user-images.githubusercontent.com/7152530/44279760-78cd6e80-a207-11e8-9b4c-7ec0fe00bd7d.png)

**Comment by stevengj** [comment]
Apparently some discretization error is allowing the initial oblique source to excite a small component of surface-parallel source (which is not absorbed by PML).

What is the amplitude at t=80 and t=131 compared to the amplitude at t=29?  (i.e. how small is it, and is it growing/unstable)?

**Comment by oskooi** [comment]
max(E(t=80.3))/max(E(t=29.2)) = `0.00319` and max(E(t=131.4))/max(E(t=29.2)) = `0.00234`. The full output from running `h5topng` which displays the data ranges is shown below. The amplitude of the residue fields appears to be decreasing albeit very slowly.
```
> h5topng -vZc bluered pw_oblique-ez-000*.h5
Using colormap "bluered" in file "/usr/local/share/h5utils/colormaps/bluered".
blue-white-red color map
3 color entries read from colormap file.
Scaling opacity by 1
data rank = 2
------
reading from "pw_oblique-ez-000007.30.h5".
data ranges from -0.000691681 to 0.000687629.
writing "pw_oblique-ez-000007.30.png" from 601x251 input data.
reading from "pw_oblique-ez-000014.60.h5".
data ranges from -0.0415372 to 0.0418406.
writing "pw_oblique-ez-000014.60.png" from 601x251 input data.
reading from "pw_oblique-ez-000021.90.h5".
data ranges from -0.298865 to 0.315304.
writing "pw_oblique-ez-000021.90.png" from 601x251 input data.
reading from "pw_oblique-ez-000029.20.h5".
data ranges from -0.376476 to 0.379225.
writing "pw_oblique-ez-000029.20.png" from 601x251 input data.
reading from "pw_oblique-ez-000036.50.h5".
data ranges from -0.377869 to 0.382921.
writing "pw_oblique-ez-000036.50.png" from 601x251 input data.
reading from "pw_oblique-ez-000043.80.h5".
data ranges from -0.131162 to 0.137293.
writing "pw_oblique-ez-000043.80.png" from 601x251 input data.
reading from "pw_oblique-ez-000051.10.h5".
data ranges from -0.0109939 to 0.0114683.
writing "pw_oblique-ez-000051.10.png" from 601x251 input data.
reading from "pw_oblique-ez-000058.40.h5".
data ranges from -0.00570208 to 0.00563102.
writing "pw_oblique-ez-000058.40.png" from 601x251 input data.
reading from "pw_oblique-ez-000065.70.h5".
data ranges from -0.00273248 to 0.00274782.
writing "pw_oblique-ez-000065.70.png" from 601x251 input data.
reading from "pw_oblique-ez-000073.00.h5".
data ranges from -0.00168477 to 0.00168026.
writing "pw_oblique-ez-000073.00.png" from 601x251 input data.
reading from "pw_oblique-ez-000080.30.h5".
data ranges from -0.00122734 to 0.00121196.
writing "pw_oblique-ez-000080.30.png" from 601x251 input data.
reading from "pw_oblique-ez-000087.60.h5".
data ranges from -0.00100849 to 0.00100284.
writing "pw_oblique-ez-000087.60.png" from 601x251 input data.
reading from "pw_oblique-ez-000094.90.h5".
data ranges from -0.000975358 to 0.000964682.
writing "pw_oblique-ez-000094.90.png" from 601x251 input data.
reading from "pw_oblique-ez-000102.20.h5".
data ranges from -0.000892442 to 0.000884068.
writing "pw_oblique-ez-000102.20.png" from 601x251 input data.
reading from "pw_oblique-ez-000109.50.h5".
data ranges from -0.000906182 to 0.000893375.
writing "pw_oblique-ez-000109.50.png" from 601x251 input data.
reading from "pw_oblique-ez-000116.80.h5".
data ranges from -0.000824479 to 0.000819492.
writing "pw_oblique-ez-000116.80.png" from 601x251 input data.
reading from "pw_oblique-ez-000124.10.h5".
data ranges from -0.000836473 to 0.000830475.
writing "pw_oblique-ez-000124.10.png" from 601x251 input data.
reading from "pw_oblique-ez-000131.40.h5".
data ranges from -0.000886532 to 0.000887753.
writing "pw_oblique-ez-000131.40.png" from 601x251 input data.
reading from "pw_oblique-ez-000138.70.h5".
data ranges from -0.000792184 to 0.000772404.
writing "pw_oblique-ez-000138.70.png" from 601x251 input data.
reading from "pw_oblique-ez-000146.00.h5".
data ranges from -0.000793948 to 0.000771864.
writing "pw_oblique-ez-000146.00.png" from 601x251 input data.
all data range from -0.377869 to 0.382921.
```

**Comment by oskooi** [comment]
This is a log-log plot of the field intensity at the source point versus the simulation time for different angles of the oblique source (`theta_in` parameter of the script). There is a nearly six orders of magnitude difference in the residual fields for the θ=0° case compared to the three with θ>0°. 

![oblique_source_field_decay](https://user-images.githubusercontent.com/7152530/44360010-525d3c80-a46e-11e8-973f-94701ee239df.png)

How can we determine if this discretization bug is related to the line source (which should be 1 pixel thick) or the implementation of Bloch-periodic boundaries with non-zero `k_point`?

**Comment by stevengj** [comment]
Since the y-directed wave looks like it is of the same frequency as the original wave, my guess is that this is caused by a spatial discretization error.  (The amplitude seems too big for roundoff errors.)   For example, the source might do something funny at the very edge of the cell, so that one pixel at each end is not sinusoidal — this would give a spatial component to the source that would excite a y-directed wave.   Increasing the resolution would decrease the amplitude of this, but only very slowly.

A workaround would be to do something to the boundary conditions or inside the PML that would attenuate this wave.  Two possible options:

* Change the boundary conditions in the x direction to be PMC instead of periodic (but still be periodic in y).   That should disallow this y-directed wave.

* Add a thin layer of scalar conductivity σ adjacent to the cell boundary (inside the PML), to attenuate y-directed waves.

**Comment by oskooi** [comment]
Neither changing the x-boundaries to a perfect magnetic conductor or adding a thin layer of conductivity produced a significant change in the results.

**Change x-boundaries to perfect magnetic conductor**
```py
sim.init_sim()
sim.fields.set_boundary(mp.High, mp.X, mp.Magnetic)
sim.fields.set_boundary(mp.Low, mp.X, mp.Magnetic)
```

**Add a thin layer of scalar conductivity inside the PML**
```py
geometry = [mp.Block(center=mp.Vector3(+0.5*sx-0.25*dpml,0,0), size=mp.Vector3(0.5*dpml,sy,0), material=mp.Medium(D_conductivity=0.1)),
            mp.Block(center=mp.Vector3(-0.5*sx+0.25*dpml,0,0), size=mp.Vector3(0.5*dpml,sy,0), material=mp.Medium(D_conductivity=0.1))]
```
Increasing the `cutoff` of the source, which reduces unwanted high-frequency components, also had no effect. 

One approach which did reduce the residue fields was simply decreasing the width of the pulse (via the `df` parameter from the script) as shown in this plot.

![oblique_source_field_decay_df](https://user-images.githubusercontent.com/7152530/44420185-24413080-a532-11e8-86c4-96db746bfdda.png)

Note that a sufficiently narrow pulse width produces residue fields which go all the way down to machine precision (i.e., `1e-16`). Perhaps this suggests that the issue is related to temporal effects?

**Comment by stevengj** [comment]
To recap, there are two issues here:

* PML, by its very nature, does not absorb waves going perfectly parallel to the PML, which are allowed here because the problem is periodic in the other direction.

* Due to some numerical error associated with the space/time discretization and/or the source, our oblique planewave source is exciting some small component in the PML-parallel direction, which doesn't decay away.

There are three possible solutions:

* Don't use PML.  Use a scalar absorber instead, which is isotropic.  Unfortunately this requires a thicker absorbing layer to suppress reflections.

* Change the source somehow to avoid exciting the PML-parallel wave, as you did above by changing `df`.

* Couple the PML with some other boundary condition or absorber that attenuates the PML-parallel waves.   How precisely to do this is still an open research problem as far as I know.

**Comment by oskooi** [comment]
Replacing the PML with a scalar absorber only affects the fields in the absorbing regions. This is shown in the figure below for various snapshots of the scalar Ez field for the two cases of PML and absorber. The isotropic absorber does indeed attenuate the fields in the absorbing region. However there are still  residue fields propagating in the periodic direction in the non-absorbing region present in both cases.

![oblique_wave_pml_vs_absorbers](https://user-images.githubusercontent.com/7152530/44749068-53bde300-aac6-11e8-9005-3966bbf4495a.png)

The two rectangular areas marked by dotted lines on the sides of each snapshot image are the absorbing regions. To suppress reflections, the length of the absorbing region for PML and absorber was increased from 1 to 5 (the wavelength is 1).

The presence of the residue fields is further demonstrated by a plot of the field intensity at the source point versus simulation time shown below.

![oblique_source_field_decay_absorber_pml](https://user-images.githubusercontent.com/7152530/44748610-fd9c7000-aac4-11e8-831a-982144190ea8.png)

These findings suggest that currently the only workaround for mitigating the residue fields is to decrease `df` as demonstrated earlier since modifying the boundary layers or conditions seems to have no effect.

**Comment by stevengj** [comment]
Since this wave isn't creating any flux into the PML, one option would be to run until the flux decays, instead of until |E|^2 decays.   As a quick test to see whether this would work, you could plot the flux as a function of time and verify that it is decaying quickly to zero.

**Comment by oskooi** [comment]
The flux in either the PML or periodic directions are not decaying to zero as shown in the two plots below. The different colored curves correspond to different values of the frequency width `df` of the source. These figures were generated by plotting the instantaneous flux at a single point at equally spaced time intervals for the two directions via e.g. in the periodic direction:

```py
mon_pt = mp.Vector3(0.5*sx-dpml-0.2*dmat,0,0)
def print_stuff(sim):
  p = sim.flux_in_box(mp.Y, center=mon_pt, size=mp.Vector3())
  print("flux:, {}, {}".format(sim.meep_time(), p.real))

sim.run(mp.at_every(7.3,print_stuff), until_after_sources=2000)
```

![oblique_pw_flux_decay](https://user-images.githubusercontent.com/7152530/44934708-b7dce300-ad22-11e8-8554-039948eff1ed.png)

Note that for the same frequency width, the flux in the PML direction is slightly smaller than that in the periodic direction. Perhaps the absence of the flux decay (which is consistent with the asymptotic *flooring* of the fields at long simulation times, demonstrated earlier in this discussion) is due to the high-frequency field components near the Nyquist limit of the Yee grid which have low group velocities and are therefore poorly absorbed by the PML. However, increasing the `cutoff` from `5` (default) to `20` did not produce any change in the results.

**Comment by stevengj** [comment]
Two remaining avenues:

* Solve the open research problem (?) of a good absorber for oblique waves in this kind of geometry.

* Implement a more accurate planewave source including numerical dispersion etcetera.  There are some references on this in the Electromagnetic Wave Source Conditions paper.

**Comment by oskooi** [comment]
It seems that this issue can only be resolved by modifying the source rather than the absorber. This is because any planewave source at oblique incidence will generate fields which propagate along X/Y/Z directions due to the intrinsic numerical dispersion of the Yee grid as described in e.g., [IEEE Trans. on Antennas and Propagation, Vol. 52, pp. 3280-7, 2004](https://www.eecs.wsu.edu/~schneidj/journal-papers/perfect-tfsf.pdf). This was verified for our example in the previous figure showing the residue flux in both the PML and periodic directions. Some of the fields in the periodic direction never reach the absorbing region and remain indefinitely in the computational cell. Thus, modifying the absorber will not significantly affect the results.

A possible workaround, discussed in the reference, is to manually impart a position-dependent phase delay to the incident wavefront to compensate for the numerical dispersion. However, this approach is only valid for a single frequency. This is a major limitation and similar to our approach of simply reducing the frequency width of the pulsed source to practically zero (which increases the overall runtime of the simulation). The main challenge, which does not seem to have been previously addressed, is to develop an approach which can be applied over a broad bandwidth.

**Comment by oskooi** [comment]
It turns out that the residue fields can be reduced for a broadband source by increasing the *size* of the source: extending it from a line to a finite-length region which spans the entire computational cell (non-absorbing part). This is shown in the two figures below which are a plot of the field intensity and flux in the periodic direction as a function of the simulation time. 

The following lines were added before the `run` function to output this data:

```py
def print_stuff(sim):
      Ez = sim.get_field_point(mp.Ez, src_pt)
      Sy = sim.flux_in_box(mp.Y, center=src_pt, size=mp.Vector3(dmat,0,0))
      print("ez:, {:.2f}, {}, {}".format(sim.meep_time(),abs(Ez)**2,abs(Sy)))
```

Results are shown for three sizes of the source: line (`src length = 0`, blue), half (`src length = 0.5*dmat`, red) and entire (`src length = 1.0*dmat`, green) computational cell. The field intensity and flux are reduced by nearly four orders of magnitude (10<sup>-6</sup> to 10<sup>-10</sup>).

![ez2_vary_source_length](https://user-images.githubusercontent.com/7152530/45325567-16197b00-b506-11e8-886a-f8c7d708a11e.png)

![flux_periodic_direction_vary_source_length](https://user-images.githubusercontent.com/7152530/45325573-1a459880-b506-11e8-80f3-e7b7f5255ac2.png)

**Comment by oskooi** [comment]
There was a bug in my original script where the `k_point` was missing a factor of `ng` (the refractive index of the default medium). The full, corrected script is shown below.

```py
import meep as mp
import math
import cmath

resolution = 40        # pixels/μm                                                                                                                                              

dpml = 1               # PML thickness                                                                                                                                          
dmat = 10              # length of material                                                                                                                                     

sx = dpml+dmat+dpml
sy = 5

cell_size = mp.Vector3(sx,sy,0)
pml_layers = [mp.PML(thickness=dpml,direction=mp.X)]

fcen = 1               # center frequency (wavelength = 1 μm)                                                                                                                   
df = 0.1               # frequency width                                                                                                                                        

ng = 1.5
glass = mp.Medium(index=ng)

# rotation angle of incident planewave; CCW about Z axis, 0 degrees along +X axis                                                                                                        
theta_in = math.radians(22.9)

# k (in source medium) with correct length (plane of incidence: XY)                                                                                                             
k = mp.Vector3(math.cos(theta_in),math.sin(theta_in),0).scale(fcen*ng)
if theta_in == 0:
  k = mp.Vector3(0,0,0)

def pw_amp(k,x0):
  def _pw_amp(x):
    return cmath.exp(1j*2*math.pi*k.dot(x+x0))
  return _pw_amp

src_pt = mp.Vector3(-0.5*sx+dpml+0.3*dmat,0,0)
sources = [mp.Source(mp.GaussianSource(fcen,fwidth=df),
                     component=mp.Ez,
                     center=src_pt,
                     size=mp.Vector3(0,sy,0),
                     amp_func=pw_amp(k,src_pt))]

sim = mp.Simulation(resolution=resolution,
                    cell_size=cell_size,
                    boundary_layers=pml_layers,
                    k_point=k,
                    default_material=glass,
                    sources=sources)

def print_stuff(sim):
  p = sim.get_field_point(mp.Ez, src_pt)
  print("ez:, {}, {}".format(sim.meep_time(), abs(p)**2))

sim.run(mp.at_every(7.3,print_stuff), until_after_sources=1000)
```
As demonstrated in the following plot, the field intensity consistently and rapidly decays to machine precision for all four angles of the pulsed planewave source. There is no need to modify the boundaries or the source properties in order for the fields to fully decay away. The source and the boundaries work as expected.

![oblique_source_field_decay](https://user-images.githubusercontent.com/7152530/47623433-b3d50380-dace-11e8-80bc-7f7aa8ff5c0f.png)
