### ISSUE TITLE
missing support for GDSII in configure script, installation instructions, and Conda packages

### ISSUE THREAD

**Issue by oskooi** [stevengj/meep#487]
The recently-added tutorial example for the GDSII import feature involving a [bidirectional coupler](https://meep.readthedocs.io/en/latest/Python_Tutorials/BidirectionalCoupler/) requires that `Meep must be configured/compiled with libGDSII for get_GDSII_prisms`. Currently, there doesn't seem to be a flag involving GDSII in the configure script for either libctl or Meep (or rather one that is documented and part of the `man` or `help` pages). Once this is resolved, it would be useful to also update the [installation instructions](https://meep.readthedocs.io/en/latest/Build_From_Source/) as well as the [Conda packages](https://meep.readthedocs.io/en/latest/Installation/#conda-packages) to include support for GDSII by default.

**Comment by ChristopherHogan** [comment]
I think `configure` just checks the default locations, including header files found in `CFLAGS` and libraries found in `LDFLAGS` for `libGDSII`, just like MPB and HDF5. I just installed it into the same prefix that I installed MPB, libctl, h5utils, etc., into. I have a libGDSII conda package created, and am in the middle of adding it to the pymeep conda packages.

**Comment by oskooi** [comment]
What about also adding a flag to the configure script (i.e., `--with-gdsii`) similar to `--without-python`, `--with-libctl`, etc. so that this feature is made more explicit to the user when building from source? If not configured with `libGDSII`, then a message should appear in the configure log stating so.

**Comment by ChristopherHogan** [comment]
`--without-python` and `-with-libctl` are not quite the same because the latter expects a directory while the former is just a binary option. Which do you want for `--with-libGDSII`? And what should the default be?

**Comment by ChristopherHogan** [comment]
Maybe it would make sense to treat it like hdf5:

If configure finds `libGDSII`, it will use it, unless the `--without-libgdsii` flag is present.

**Comment by HomerReid** [comment]
> Currently, there doesn't seem to be a flag involving GDSII in the configure script for either libctl or Meep

Sure there is, on line 433 of `meep/configure.ac,` which goes through the standard process of looking first for the header file, then for the library binary, and (if successful) adds `-lGDSII` to the linker command line and `#defines HAVE_LIBGDSII 1` to `meep/config.h`. 

If the configure script can't find either the GDSII header or the library binary, it does issue a warning to that effect, with the reasons documented in `config.log`. The warning isn't particularly prominent among the thousands of lines produced by the `configure` script, but it's all done in the standard way from which a knowledgeable user would be able to figure out what's going on.

I'm not clear on the purpose of the `--without-libGDSII` flag. Are there people who will have installed `libGDSII` but *don't* want to build meep with it?

**Comment by stevengj** [comment]
Similar to how we deal with `harminv` and other optional libraries, I think we should just continue to link libGDSII if it is present, and give a runtime error if someone tries to use GDSII when `meep` is not linked with GDSII.

In the future, we might make this more friendly by printing a summary at the end of the configure output listing which optional features have been enabled.
