### ISSUE TITLE
the issue with the installation with python

### ISSUE THREAD

**Issue by chenxinxian** [stevengj/meep#49]
Hi,

I can compile meep --without-python, But if I turn on the python option, I will have the following error message, 
" No rule to make target `../src/libmeep.la', needed by `_meep.la'.  Stop."

Thanks,

Xin

**Comment by stevengj** [comment]
The Python stuff is currently experimental; I wouldn't recommend using it.

(Maybe we should have kept all of the Python stuff on a branch while we worked on it?)

cc @ChristopherHogan
