### ISSUE TITLE
Python API for GDSII regions

### ISSUE THREAD

**Issue by oskooi** [stevengj/meep#506]
The recently added [GDSII import tutorial example](https://meep.readthedocs.io/en/latest/Python_Tutorials/BidirectionalCoupler/) involves a utility function `get_center_and_size` which returns the `center` and `size` of a C++ `meep::volume` object returned by `get_GDSII_volume`. Given that `get_center_and_size` is necessary for parsing rectilinear objects (i.e., sources and monitors) which can be part of the GDSII file itself, it would be convenient to add this function to the Python interface.

**Comment by HomerReid** [comment]
An alternative possibility would be to add optional keywords like `GDSIIFile` and `GDSIILayer` to the

**Comment by oskooi** [comment]
Wouldn't it be more convenient if `get_GDSII_volume` just returned a Python `Volume` directly rather than a `meep::volume`? The current convention of wrapping `get_center_and_size` around `get_GDSII_volume` seems odd.

**Comment by stevengj** [comment]
Something like `mp.FluxRegion(gdsii=('geom.gds', port1_layer, zmin, zmax))` seems like it would be convenient.

**Comment by stevengj** [comment]
If we support other filetypes in the future besides GDSII, it might be cleaner to do something like:
```jl
mp.FluxRegion(volume=gdsiivol('geom.gds', port1_layer, zmin, zmax))
```
where `volume` is either a Python `Volume` or a C++ `meep::volume`
