### ISSUE TITLE
missing output_poynting routine

### ISSUE THREAD

**Issue by oskooi** [stevengj/meep#512]
The documentation page [Synchronizing the Magnetic and Electric Fields](https://meep.readthedocs.io/en/latest/Synchronizing_the_Magnetic_and_Electric_Fields/) references a function `output_poynting` which does not seem to exist (it may possibly have been deprecated/removed at some point?). There is also no mention of this function in [Python User Interface](https://meep.readthedocs.io/en/latest/Python_User_Interface/).

`output_poynting` is based on the existing `flux_in_box` routine but will return the full complex value for **E\*** × **H** (rather than just the real part) over the entire computational cell. This is similar to other such routines including `output_tot_pwr`, `output_epsilon`, etc.

**Comment by ChristopherHogan** [comment]
It exists as `mp.output_poynting`. Maybe you were trying `sim.output_poynting`? I'll add the it to the docs.

**Comment by oskooi** [comment]
The `output_poynting` routine defined in `meep/python/simulation.py` is for MPB compability as it is stated as such in that file and also described in the [MPB documentation](https://mpb.readthedocs.io/en/latest/Python_User_Interface/). It is not a native Meep routine which would have its function header defined in `src/meep.hpp`. Also, no such routine is defined in the Scheme interface for Meep.

**Comment by ChristopherHogan** [comment]
`output-poynting` does exist in the scheme interface. It's defined by a macro [here](https://github.com/stevengj/meep/blob/master/scheme/meep.scm.in#L949). It has the same comment about MPB, and I believe this is the function that "Synchronizing the Magnetic and Electric Fields" references. Maybe @stevengj can clarify.

**Comment by stevengj** [comment]
Looks like the routine just needs to be documented, and the Synchronizing page needs to be clarified to say that the Poynting flux is Re[E* x H] (since it comes via `derived_component`, see the docs for that)
