### ISSUE TITLE
missing Lorentzian susceptibility terms in preamble output info

### ISSUE THREAD

**Issue by oskooi** [stevengj/meep#561]
If a material is defined with two distinct [Lorentzian susceptibility](https://meep.readthedocs.io/en/latest/Materials/#material-dispersion) terms which have identical frequency ω and decay rate γ but different strength σ then only one of the terms appears in the preamble output info.

As an example, uniaxial silicon dioxide (`SiO2_aniso`) which was recently added to the [material library](https://github.com/stevengj/meep/blob/master/python/materials.py#L1152-L1182) contains four Lorentzian terms. Two of of these terms have the same frequency and decay rate. The output (shown below) only contains three of these terms.

**Simulation Script**
```py
import meep as mp
from meep.materials import SiO2_aniso

sim = mp.Simulation(default_material=SiO2_aniso,
                    cell_size=mp.Vector3(1,1,1),
                    resolution=20)

sim.init_sim()
```

**Output**
```
Initializing structure...
Working in 3D dimensions.
Computational cell is 1 x 1 x 1 with resolution 20
time for set_epsilon = 0.011718 s
lorentzian susceptibility: frequency=9.89653, gamma=0
lorentzian susceptibility: frequency=0.1, gamma=0
lorentzian susceptibility: frequency=9.97083, gamma=0
```
It would be useful to show *all* Lorentzian terms by adding the `sigma` values to the output. However, since σ can be position dependent and thus have multiple values, we can just show the maximum σ to avoid ambiguity.

**Comment by stevengj** [comment]
Internally, Meep considers this to be "one material" with a position-dependent σ.
