### ISSUE TITLE
fix binary_grating test

### ISSUE THREAD

**Issue by stevengj** [stevengj/meep#568]
This is temporarily disabled (f1d972dfd39cf91e13ba92191fc8d866fe6bf899) because it appears to be subject to occasional random failures in MPI mode.  Not clear what is causing it.

**Comment by oskooi** [comment]
After some investigation, it seems there is a likely bug somewhere in `fields::get_mode_flux_overlap` (and also `fields::get_mode_mode_overlap`) for the case involving MPI *and* a non-zero `k_point`. The mode coefficients are equivalent for the serial and parallel case when `k_point` is `0`. This is the first part of the test.

For the second part of the test where `k_point` is non-zero, `fields::get_eigenmode` produces identical results (`kdom` values as well as the field profiles) for the serial and parallel case. This demonstrates that the MPB-related functions are working correctly. The only difference in the results were the values of the mode coefficients.

Perhaps @HomerReid can provide further insights?

**Comment by oskooi** [comment]
Unfortunately, it seems that #578 does not resolve this issue. As a further demonstration, the same erratic behavior is observed after replacing the random number generator `rand_r` in `src/mpb.cpp:342`:

```cpp
ASSIGN_SCALAR(H.data[i], rand_r(&seed) * 1.0/RAND_MAX, rand_r(&seed) * 1.0/RAND_MAX);
```
with just hard-coded random values:

```cpp
ASSIGN_SCALAR(H.data[i], 0.548724, 0.837532);
```
This would suggest that the MPB phase is in fact not the source of the bug. It doesn't seem that random numbers are used anywhere else in `src/mpb.cpp` or functions related to `get_eigenmode_coefficients`. 

Another possibility: what about the MPI calls to communicate MPB fields among different Meep chunks when MPB has been built serially?

**Comment by stevengj** [comment]
In case there is still something that is causing the MPB solution to be nondeterministic, i.e. different on different processes (when the eigenmode region spans multiple processes), a simple way to synchronize them should be to add:
```c
broadcast(0, (double*) H.data,  2 * H.n * H.p);
```
in mpb.cpp before line 435 (before the call to `maxwell_compute_h_from_H`).

**Comment by HomerReid** [comment]
On line 853 of `src/dft.cpp`, try adding this:

```
debug_printf("%e %e \n",real(overlap), imag(overlap));
```

This will produce files titled `debug_out_0`, `debug_out_1`, etc. containing the contributions of each process to the overlap integrals that enter the numerator and denominator of the mode-decomposition coefficient. For a multi-processor run, the numbers in all files should add up to the single number in `debug_out_0` for a single-processor run. Things to check:

-- Does the discrepancy affect only the numerator, or only the denominator, or both?
-- For e.g. a 6-processor run, are the contributions of all 6 processes equally screwy, or are most correct with just one errant process being the outlier?

**Comment by oskooi** [comment]
Steven's suggestion of synchronizing the processes using `broadcast` seems to have fixed the problem. The results are no longer nondeterministic.

**Comment by stevengj** [comment]
Hooray!

Rather than going to the trouble of tracking this down, it might be better to just skip the MPB calculations on all processes other than the master node, since there's no point in duplicating this work.
