### ISSUE TITLE
GDSII layer dimensions not matching Meep cell

### ISSUE THREAD

**Issue by oskooi** [stevengj/meep#586]
As reported originally in #555 and even after updates to the GDSII file [examples/coupler.gds](https://github.com/stevengj/meep/blob/master/python/examples/coupler.gds) following the merging of #585, the (corrected) dimensions of `layer 0` (`34.4` μm x `8.0` μm) of this file do not match Meep's cell dimensions (`34.4` μm x `7.8` μm). The discrepancy is only in the `y` direction. This is demonstrated in the following output from [examples/coupler.py](https://github.com/stevengj/meep/blob/master/python/examples/coupler.py):

```
Using MPI version 3.0, 1 processes
-----------
Initializing structure...
Working in 2D dimensions.
Computational cell is 34.4 x 7.8 x 0 with resolution 25
     prism, center = (-9.09425,1.31149,0)
          height 0, axis (0,0,1), 174 vertices:
...
...
```

**Comment by HomerReid** [comment]
This is not a bug---the script is doing what it is supposed to. The computational cell size is not necessarily equal to the size specified in the `.gds` file. Instead, the python script sets the cell size based on the value of the "-d"  command-line argument, which sets the minimal separation distance of the coupler branches. To achieve the specified distance, the python script displaces the upper and lower branches symmetrically and expands or shrinks the vertical cell size accordingly. In the bare structure described by `coupler.gds`, the coupler-coupler separation is 0.3 and the cell size in the Y direction is 8.0. However, in `coupler.py` the default value of the `-d` option is 0.1. Thus, when initializing the geometry the script displaces the upper branch downward by 0.1 and the lower branch upward by 0.1 (to ensure a minimum separation of 0.3 - 0.1 - 0.1 = 0.1) and shrinks the size of the cell by 0.1+0.1 = 0.2.
