### ISSUE TITLE
Whether guile2.0.11 is compatible with meep

### ISSUE THREAD

**Issue by tianyajq** [stevengj/meep#592]
Dear everyone,
I've use VMware and ubuntu to install meep. But I  meet the problem of 'ERROR: In procedure delete-meep-volume: Wrong type argument in position 1: #<finalized smob 5596f44f3120>
ERROR: In procedure %run-finalizers:
ERROR: In procedure delete-meep-volume: Wrong type argument in position 1: #<finalized smob 5596f44f3500>'
After searching the suggestion on the internet, I downgrade the guile version to guile2.0.11. However, this problem still exists.
What can I do to solve it.
Here's the error message：
-----------
Initializing structure...
Working in 2D dimensions.
Computational cell is 16 x 16 x 0 with resolution 10
     cylinder, center = (0,0,0)
          radius 2, height 1e+20, axis (0, 0, 1)
          dielectric constant epsilon diagonal = (11.56,11.56,11.56)
     cylinder, center = (0,0,0)
          radius 1, height 1e+20, axis (0, 0, 1)
          dielectric constant epsilon diagonal = (1,1,1)
Halving computational cell along direction y
time for set_epsilon = 0.058038 s
-----------
creating output file "./rt-eps-000000.00.h5"...
Backtrace:
In ice-9/boot-9.scm:
 160: 12 [catch #t #<catch-closure 5596f3a25920> ...]
In unknown file:
   ?: 11 [apply-smob/1 #<catch-closure 5596f3a25920>]
In ice-9/eval.scm:
 432: 10 [eval # #]
 432: 9 [eval # #]
In unknown file:
   ?: 8 [primitive-load "rt.ctl"]
In ice-9/eval.scm:
 432: 7 [eval # #]
In ice-9/boot-9.scm:
 703: 6 [map #<procedure 5596f45bd060 at ice-9/eval.scm:416:20 (a)> #]
In ice-9/eval.scm:
 399: 5 [eval # #]
 387: 4 Exception thrown while printing backtrace:
ERROR: In procedure delete-meep-volume: Wrong type argument in position 1: #<finalized smob 5596f44f3120>

ERROR: In procedure %run-finalizers:
ERROR: In procedure delete-meep-volume: Wrong type argument in position 1: #<finalized smob 5596f44f3500>

Some deprecated features have been used.  Set the environment
variable GUILE_WARN_DEPRECATED to "detailed" and rerun the
program to get more information.  Set it to "no" to suppress
this message.

**Comment by ChristopherHogan** [comment]
Hi,

How did you install Meep? Meep >= 1.6.0 should work with any version of
Guile but you will have to build from source, following the instructions
here:
https://meep.readthedocs.io/en/latest/Build_From_Source/#building-from-source
.

Chris

**Comment by jonsger** [comment]
@ChristopherHogan Includes "any version of Guile" even guile 2.2?

**Comment by oskooi** [comment]
Yes. Support for Guile 2.2 has been enabled via #419 and #458.

**Comment by tianyajq** [comment]
> Yes. Support for Guile 2.2 has been enabled via #419 and #458.

Thank you! I've solved this problem
