### ISSUE TITLE
configure can't find ctl.h

### ISSUE THREAD

**Issue by JohnWeiner** [stevengj/meep#61]
I am trying to install meep and company on an iMac running 10.12.5 (Sierra). Harminv and libctl install without error.  When I try to install meep itself, however, the configure script complains that it cannot find the ctl.h header.

configure:25526: error: Couldn't find the ctl.h header file for libctl.
ac_cv_header_ctl_h=no

However ctl.h is where it is supposed to be.  A "find -name ctl.h", results in
/usr/local/include/ctl.h
/usr/local/share/libctl/ctl.h

The config.log does not appear to be any more enlightening.  Is there some way to know where the configure script is looking for ctl.h?
Any ideas?

**Comment by oskooi** [comment]
`/usr/local` is considered a non-standard location by some compilers. You will therefore need to set the `LDFLAGS` and `CPPFLAGS` environment variables as explained in the [installation guide](http://meep.readthedocs.io/en/latest/Installation/#paths-for-configuring). Also, if you are building as a shared library, you can try adding the dynamic linker/loader library to the configure script: `./configure LIBS=-ldl`.

**Comment by JohnWeiner** [comment]
Yes,
 ./configure CPPFLAGS=-I/usr/local/include 
allowed the configure script to run to completion and generated a Makefile.  When executing with make, however, these errors were generated,
meep_wrap.cxx:1384:10: error: use of undeclared identifier 'SCM_VECTORP'
  return SCM_VECTORP(o) && SCM_VECTOR_LENGTH(o) == 3;
         ^
meep_wrap.cxx:1384:28: error: use of undeclared identifier 'SCM_VECTOR_LENGTH'
  return SCM_VECTORP(o) && SCM_VECTOR_LENGTH(o) == 3;

**Comment by JohnWeiner** [comment]
Looking in config.log, I see a recurrent error, 
configure: failed program was:
/* confdefs.h */
Maybe this is a header file that declares SCM_VECTOR_LENGTH?
