### ISSUE TITLE
Compile Error related verbose `get_eigenmode_coeffcients`

### ISSUE THREAD

**Issue by soamaven** [stevengj/meep#613]
Master branch and `swig` aren't playing nicely anymore. Looks like its related to ead020ec82ac4c2dbe42aa7914b7925a0e9f721c .
```
meep_wrap.cxx:45699:136: error: no matching function for call to ‘meep::fields::get_eigenmode_coefficients(SwigValueWrapper<meep::dft_flux>&, const meep::volume&, int*&, int&, int&, double&, double&, std::complex<double>*&, double*&, meep::vec (*&)(double, int, void*), void*&, meep::vec*&, meep::vec*&, bool&)’
   (arg1)->get_eigenmode_coefficients(arg2,(meep::volume const &)*arg3,arg4,arg5,arg6,arg7,arg8,arg9,arg10,arg11,arg12,arg13,arg14,arg15);
                                                                                                                                        ^
In file included from meep-ctl.hpp:5:0,
                 from meep_wrap.cxx:1404:
/path/to/meep/install/include/meep.hpp:1511:8: note: candidate: void meep::fields::get_eigenmode_coefficients(meep::dft_flux, const meep::volume&, int*, int, int, double, double, std::complex<double>*, double*, meep::kpoint_func, void*, meep::vec*, meep::vec*)
   void get_eigenmode_coefficients(dft_flux flux, const volume &eig_vol,
        ^
/path/to/meep/install/include/meep.hpp:1511:8: note:   candidate expects 13 arguments, 14 provided
```

previous commit compiles just fine for me

**Comment by oskooi** [comment]
This should be working since it has been tested. Perhaps there's something wrong with your installation? Try running `make distclean` and rebuilding or start with a fresh build tree. Also, which version of SWIG are you using? What happens when you upgrade to the latest version?

**Comment by soamaven** [comment]
I tried removing and  re-cloning the entire branch before building, I think that would be equivalent to `make distclean` no? Using `swig v3.0.12` which is the latest version.

**Comment by soamaven** [comment]
@woodenToaster That was the problem. I was recompiling into a path with the previous version, and the include path had the old `meep.hpp` Thanks!
