### ISSUE TITLE
Return more Harminv Data

### ISSUE THREAD

**Issue by soamaven** [stevengj/meep#620]
It would be nice to work with the full output of Harminv in script when using `run_k_points`. Right now `run_k_points` only outputs the frequencies, but not the Q, amplitude, or error data.

This shouldn't be too hard by changing the line below, just a matter of figuring out how to output it so that it doesn't break tests and is backwards compatible. I'd do it if there is direction on how to not break things.

https://github.com/stevengj/meep/blob/5cd39bd62c2aa35ba9d71d15758134be56975dc6/python/simulation.py#L1137

Edit: Now that I think about it, there would be a round-about way to get the data, using an external loop over k-points and access function wrapped in `mp.at_end` to get to the `harminv` object directly.

**Comment by stevengj** [comment]
One option is to have a `run_kpoints_harminv` function that returns a tuple of `all_freqs, harminvs` where `all_freqs` is the same as the current `run_kpoints` return value and `harminvs` is a list of `Harminv` objects (one per k point).   (`run_kpoints` would then just be a wrapper around this that discards the second output.)

Another option would be to just document the lower-level function `run_kpoint` (replacing the current `_run_kpoint`) that runs a single k point and returns the `Harminv` object.   The `run_kpoints` higher-level function would then call this function and continue to return `all_freqs`.
