### ISSUE TITLE
Cannot make meep on macOS Sierra

### ISSUE THREAD

**Issue by JohnWeiner** [stevengj/meep#64]
I am using this "issue" space to record my attempts to get meep installed on macOS Sierra (10.12.5).  It is probably best to scroll down to the bottom and read it in reverse chronological order to get an idea of the present state of the problem.

After downloading meep-master from GitHub, ./configure LDFLAGS=-L/usr/local/lib CPPFLAGS=-I/usr/local/include goes to completion and generates a make file.  However, make. terminates with errors:

meep_wrap.cxx:1394:10: error: use of undeclared identifier 'SCM_VECTORP'
  return SCM_VECTORP(o) && SCM_VECTOR_LENGTH(o) == 3;
         ^
meep_wrap.cxx:1394:28: error: use of undeclared identifier 'SCM_VECTOR_LENGTH'
  return SCM_VECTORP(o) && SCM_VECTOR_LENGTH(o) == 3;
                           ^
meep_wrap.cxx:53286:63: error: address of overloaded function '_wrap_do_harminv' does not match required type 'void'
  scm_c_define_gsubr("do-harminv", 0, 0, 1, (swig_guile_proc) _wrap_do_harminv);

I tried modifying the Makefile.am in /libctl subdirectory, as suggested on the DarkAlex blog, https://darkalexwang.github.io/2016/10/06/python-meep-install-mac/, but either I don't know how to apply the edits properly or the edits are no longer effective.  In any case the same errors appear after executing the make command.

Does anybody know if there is a simple edit somewhere to the "undeclared identifier" problem?
and/or "address of overloaded function" problem?

**********************************************
**Update to this continuing issue: 6 July 2017:**
**********************************************
I tried Oskool's suggestion below, following the recipe that one finds here, https://www.mail-archive.com/meep-discuss@ab-initio.mit.edu/msg05719.html.  I followed the recipe by using "home-brew uninstall guile" to get rid of guile 2.2.2.  Then I downloaded guile 2.0.11 from the gnu index site, https://ftp.gnu.org/gnu/guile/ and tried to execute the configure, make, make install sequence.  I was able to get the ./configure script to run to the end without error by using ./configure --prefix=/usr/local --enable-deprecated=YES LDFLAGS='-L/usr/local/opt/libffi/lib -L/usr/local/opt/readline/lib' CPPFLAGS='-I/usr/local/Cellar/libffi/3.2.1/lib/libffi-3.2.1/include -I/usr/local/opt/readline/include'
The long path CPPFLAGS was necessary to find ffi.h because home-brew did not symlink libffi to /usr/local.  I thought setting "--enable-deprecated=YES" might be helpful for using deprecated stuff in guile that still works.  However make still has problems:

"Undefined symbols for architecture x86_64:
  "_clock_getcpuclockid", referenced from:
      _scm_init_stime in libguile_2.0_la-stime.o
  "_ffi_call", referenced from:
      _scm_i_foreign_call in libguile_2.0_la-foreign.o
  "_ffi_closure_alloc", referenced from:
      _scm_procedure_to_pointer in libguile_2.0_la-foreign.o"

  etc, etc (there are lots more "Undefined symbols for architecture x86_64"). The list of undefined symbols terminates with

"ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)"

So I cannot proceed with the meep installation recipe until I get guile 2.0.11 made and installed.  Does anybody know if there is a workaround for the "undefined symbols" problem?

*********************************************
**Update to this continuing issue: 7July 2017**
**********************************************
I tried a different approach, downloading guile 2.0.11 from the GitHub repository and executing the autogen.sh script.  It produced an error message, 
"configure.ac:927: error: possibly undefined macro: AM_GNU_GETTEXT
      If this token and others are legitimate, please use m4_pattern_allow."
I edited the configure.ac file by commenting out line 927 and using 'm4_pattern_allow' for AM_GNU_GETTEXT.  This tactic allowed the generation of the configure file, but from there the story is the same as yesterday.  The linking stop here:

"CCLD     libguile-2.0.la
Undefined symbols for architecture x86_64:
  "_clock_getcpuclockid", referenced from:
      _scm_init_stime in libguile_2.0_la-stime.o
...
...
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)"

**********************************************
**Update to this continuing issue: 8 July 2017:**
**********************************************

According to https://www.gnu.org/software/gettext/manual/html_node/AM_005fGNU_005fGETTEXT.html,
AM_GNU_GETTEXT is a macro in a file called gettext.m4.  Maybe autogen.sh doesn't find AM_GNU_GETTEXT because it does not look in the directory where gettext.m4 resides.  I installed gettext with home-brew, thinking that perhaps getttext was missing from the macOS.  A "find" on gettext.m4 locates it in /usr/local/Cellar/gettext/0.19.8.1/share/aclocal/gettext.m4.  Is there some way to get autogen.sh or configure.ac to look in this path?

**********************************************
**Update to this continuing issue: 9 July 2017:**
**********************************************

I think I have solved the AM_GNU_GETTEXT missing macro problem.  Here is what I do to get to a ./configure file for guile-2.0.11: First download the compressed tar package (I think these are called "tarballs") from the GitHub repository and tar -xvf to get the files in a guile-2.0.11 directory.  One of the files is autogen.sh which is a bash script that calls configure.ac, an "autotool"  that generates the appropriate configure executable.  However, configure.ac stops with an error because it cannot find gettext.m4 in the m4 subdirectory.  I installed gettext using home-brew, which puts other m4 (apparently more up-to-date) files in /usr/local/Cellar/gettext/0.19.8.1/share/aclocal. Then I just copied all the m4 files from /usr/local/Cellar... to .../guile-2.0.11/m4, then executed the autogen script again.  Now it runs to completion and generates a configure executable.  I then do

 ./configure LIBFFI_CFLAGS="-I/usr/local/opt/libffi/include -I/usr/local/Cellar/libffi/3.2.1/lib/libffi-3.2.1/include"  LIBFFI_LIBS="-L/usr/local/opt/libffi/lib" LDFLAGS="-L/usr/local/opt/gettext/lib -L/usr/local/lib -L/usr/local/opt/readline/lib -L/usr/local/Cellar/gettext/0.19.8.1/lib" CPPFLAGS="-I/usr/local/opt/gettext/include -I/usr/local/include -I/usr/local/opt/readline/include -I/usr/local/Cellar/gettext/0.19.8.1/include".  

The LIBFFI_CFLAGS and LIBFFI_LIBS are necessary because the ffi home-brew installation puts the ffi files in /usr/local/opt/libffi.  Some of the LDFLAGS and CPPFLAGS may be superfluous but I don't dare change them because with these ./configure options the executable runs to completion and generates a make file in .../guile-2.0.11.  Now I "make" which after awhile stops and generates the error message indicated above.  Here it is again just for convenience:

Making all in libguile
/Applications/Xcode.app/Contents/Developer/usr/bin/make  all-am
  CCLD     libguile-2.0.la
Undefined symbols for architecture x86_64:
  "_clock_getcpuclockid", referenced from:
      _scm_init_stime in libguile_2.0_la-stime.o
  "_ffi_call", referenced from:
      _scm_i_foreign_call in libguile_2.0_la-foreign.o
  "_ffi_closure_alloc", referenced from:
      _scm_procedure_to_pointer in libguile_2.0_la-foreign.o

and a few more "_ffi_" type of errors.  The message terminates with

ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation).  

Fishing around on Google, using "_ffi_" as bait, I found this: https://github.com/ocamllabs/ocaml-ctypes/issues/74 which describes similar symptoms.  The problem apparently is that the macOS or Xcode comes with an out-of-date ffi library and the linker finds it in the search path before it looks in /usr/local/Cellar/libffi/3.2.1/lib, where the up-to-date ffi library is.  Can someone help me modify the search path when the linker is invoked?  Should I try to modify the make file in /Applications/Xcode.app/Contents/Developer/usr/bin/make ?  Apparently one can also modify pkg-config, but I don't dare start messing around in these things without having a decent idea of what I am doing.

The first error message,  "_clock_getcpuclockid", referenced from:
      _scm_init_stime in libguile_2.0_la-stime.o, is a qualitatively different problem, I would guess.  

**********************************************
**Update to this continuing issue: 12 July 2017:**
**********************************************

I added the following library path to the ./configure command,

-L/Users/johnweiner/Downloads/guile-2.0.11/lib

because the first missing symbol, "_clock_getcpuclockid" is associated with a header file, time.h.  I found time. h in the above library path and ran ./configure with all the search path options again.  Then "make V=1".  The "V=1" option shows the compile and link commands and files explicitly as the make file executes.  However, the problem remains unchanged.  

**********************************************
**Update to this continuing issue: 14 July 2017:**
**********************************************

Finally figured out why the ffi symbols could not be found.  The linker must be told where to find the relevant library and to link it, LIBFFI_LIBS="-L/usr/local/opt/libffi/lib -lffi".  The "-lffi" flag had been missing all along.  Including it in LIBFFI_LIBS eliminates all the errors associated with undefined _ffi_ symbols.  The one remaining is 

Undefined symbols for architecture x86_64:
  "_clock_getcpuclockid", referenced from:
      _scm_init_stime in libguile_2.0_la-stime.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Apparently this failure is due to a call in libguile/stime.c to "clock_getcpuclockid".  There is a note about it in bug#23870, http://lists.gnu.org/archive/html/bug-guile/2016-06/msg00252.html.  There is a patch to fix the problem for macOS, https://gist.github.com/rahulg/baa500e84136f0965e9ade2fb36b90ba/revisions, but I'm not sure how to apply this patch.

Update to this continuing issue: 18 July 2017:

The patch does not involve a lot of text so I just typed it into the pertinent file, .../libguile/stime.c, and then the usual "configure, make" sequence.  The error remained unfixed.  Finally I just downloaded a later version of guile in which the problem with stime.c was supposedly fixed (http://lists.gnu.org/archive/html/bug-guile/2017-03/msg00000.html). Then I replaced the stime.c from Guile-2.0.11 with the stime.c from the later version.  Then configure and make.  This time make goes to completion with lots of warnings but no errors. After sudo make install Guile-2.0.11 was finally installed and seemed to be functioning ok...at least I was able to get a guile prompt and the command, guile --version gives the correct version.

Now with guile installed I proceeded to install meep-1.3 which I downloaded directly from the meep MIT Ab Initio site.  I had some initial problems getting meep-1.3 to "make" because somewhere the linker was getting a flag to a guile path that no longer, if ever, existed.  Possibly this residual path remained from an earlier attempt to install guile with home-brew...before learning that Guile-2.2 would not work with meep.  Even though I uninstalled the home-brew installation the linker path persisted.

Now meep-1.3 installs!  I created the first tutorial ctl file for the straight waveguide.  The program ran and generated the two expected h5 files.  Now, however, the 5hutils command, h5topng, generates a segmentation fault, but h5utils problems should be the subject of a different "issue".  For the time being at least I am assuming that the h5 files generated by the straight waveguide are not defective, and the problem is with h5utils.

Any suggestions would be greatly appreciated.

John

**Comment by oskooi** [comment]
Have you tried this [installation guide for Sierra based on HomeBrew](https://www.mail-archive.com/meep-discuss@ab-initio.mit.edu/msg05719.html) which was posted in the meep-discuss mailing list?

**Comment by JohnWeiner** [comment]
Thanks, I did not know about this link, and I will try it.  I tried to get myself on the mailing list a few times in late June, but I never got any response from my requests (never got any email back from the site).  Is there any reason why I might not be able to get on the list?

Best regards,

John
