### ISSUE TITLE
h5topng seg faults in macOS Sierra

### ISSUE THREAD

**Issue by JohnWeiner** [stevengj/meep#70]
Since h5utils is part of the meep constellation, I thought this might be the appropriate venue for this problem.  After having installed meep-1.3 on macOS Sierra (see issue #64), I find that, when invoking the h5topng command with the appropriate options (-S3) operating on the file, test1-eps-000000.00.h5, generated by the first tutorial meep program (straight wave guide), I get a memory error,

h5topng -S3 test1-eps-000000.00.h5
h5topng(28360,0x7fffe584e3c0) malloc: *** mach_vm_map(size=18446744049097375744) failed (error code=3)
*** error: can't allocate region
*** set a breakpoint in malloc_error_break to debug
h5topng error: out of memory

subsequent invocations of h5topng simply results in a segmentation fault.  The h5utils package was downloaded from the meep MIT Abinitio  site and the appropriate patch, hdf5_h5utils_libpng_patch, was applied with the patch command.  The "configure", "make", "sudo make install" without incident.

I have no reason to believe the h5 file is defective although I don't know how to verify this independently.  The "meep test1.ctl >& test1.out" command runs, produces the h5 file, and no errors.

Does anybody know how to diagnose the error allocation problem and fix it?

**Comment by stevengj** [comment]
I've just pushed an h5topng repository on Github, so we can move this issue there: https://github.com/stevengj/h5utils

**Comment by js1990** [comment]
> I've just pushed an h5topng repository on Github, so we can move this issue there: https://github.com/stevengj/h5utils

I installed from there and I'm having a slightly different problem.
I get 
zsh: command not found: h5topng
I don't understand why.

My mac is Catalina

**Comment by stevengj** [comment]
> zsh: command not found: h5topng

You need to make sure that `h5topng` is installed to someplace in your PATH.   (Hopefully you did `make install`, too.)
