### ISSUE TITLE
meep fails to run at command line, no arguments

### ISSUE THREAD

**Issue by acmcclung** [stevengj/meep#90]
Installed from source on CentOS 7.3.1611 with guile 2.0.9. MPB works just fine. Any thoughts?

```
Backtrace:
In ice-9/boot-9.scm:
 157: 10 [catch #t #<catch-closure 14beb20> ...]
In unknown file:
   ?: 9 [apply-smob/1 #<catch-closure 14beb20>]
In ice-9/eval.scm:
 432: 8 [eval # #]
 432: 7 [eval # #]
In unknown file:
   ?: 6 [primitive-load "/usr/local/share/meep/meep.scm"]
In ice-9/eval.scm:
 432: 5 [eval # #]
 432: 4 [eval # #]
In unknown file:
   ?: 3 [primitive-load "/usr/local/share/meep/meep-enums.scm"]
In ice-9/eval.scm:
 453: 2 [eval #<memoized (define Centered Dielectric)> ()]
 393: 1 [eval #<memoized Dielectric> ()]
In unknown file:
   ?: 0 [memoize-variable-access! #<memoized Dielectric> #<directory # 14aec60>]

ERROR: In procedure memoize-variable-access!:
ERROR: Unbound variable: Dielectric
```

**Comment by stevengj** [comment]
Is this the git source or the released version?

**Comment by acmcclung** [comment]
This is the 1.3 release.

**Comment by acmcclung** [comment]
I am not sure exactly why, but I was able to resolve the issue by following the [instructions for Ubuntu 16.04](https://www.mail-archive.com/meep-discuss@ab-initio.mit.edu/msg05819.html) as closely as I could in CentOS, replacing the github sources for harminv, libctl, mpb and meep with the latest released packages. Everything apparently works now&mdash;sorry to sound the alarm.
